export const SPECIAL_INSTRUCTIONS_PATTERNS = [
  'with AZT/3CT',
  'with ABC/3CT',
  'preferably within 72 hours but can be given up to 7 days after delivery',
  'Preferably within 72 hours but may be given up to 7 days following management of miscarriage',
  'preferably within 72 hours but may be given up to 7 days following TOP',
  'Uterine Bleeding, abnormal',
  'day 1, day 2 and day 15',
  'after every nappy change',
  'within 12 hours of delivery',
  'given slowly at a rate not > 5 ml/minute',
  'as per severity reduce treatment',
  'days 1-4 of cycle',
  'only 12 hours after administration of Factor IX complex or factor VIII inhibitor',
  'glucose tolerance test',
  'on waking, midday, 16h00',
  'bolus and increase dextrose concentration in the infusion',
  'with rescuscitation and maintenance fluids',
  /(dilute and )?apply .*/i,
  'bag 1',
  'bag 2',
  /do not .*/i,
  /not be .*/i,
  /and refer.*/,
  'from day 12-21',
  /^.* prior to surgery/i,
  /(refer to.*)/i,
  'thereafter',
  'before extraction',
  /(age dependant)/i,
  'after each diarrhoeal stool',
  'before and after each bowel action',
  'at start of transfusion',
  'night before',
  '30 minutes to 1 hour before procedure',
  '2 hours prior to procedure',
  'refer to STGs',
  'See weight-dose table',
  'Quantity dependant on size of affected area',
  'rapid IV push',
  'rapid flush',
  'into rectum',
  /\bbolus\b/i,
  /\bboluses\b/i,
  'If meningitis suspected',
  'Mix Dextrose 50% with 8ml/kg water for injection to make',
  'Small volume as test',
  '1 unit for each unit of emergency blood transfused',
  'To be calculated according to STG',
  'Topical application - dose dependant on size of affected area. Daily application',
  'topical',
  'after every 2nd shock',
  '+- 55mg elemental iron',
  /^elemental$/i,
  '1g KCl = 13mEq; 1 mL 15% KCl = 2 mmol; 1 mEq = 1 mmol',
  '13 x 400mg tablets per 2L normal saline (sodium chloride 0.9%) for wound irrigation 400mg per 35cm2. applied twice daily',
  /^(reduce.*)$/i,
  /^(until.*)$/i,
  /\bfirst dose\b/i,
  /\bsecond dose\b/i,
  /dosed according to therapeutic range/i,
  'crushed to soak gauze',
  'maximum = 10 mg on day 1',
  /^Apply\b/i,
  /^bath$/i,
  /^Wash\b/i,
  /^Flush wound\b/i,
  /^Nebulise\b/i,
  /^see range$/i,
  /^volume for volume$/i,
  /^Used as dressing\b/i,
  /^Dilution required\b/i,
  /^to soak gauze\b/i,
  /^use maximum allowable dose$/i,
  /^(Treble|Double) \w+ replacement until recovery\b/i,
  /^(infants start at .+)$/i,
  /^(equivalent to .+)$/i,
  /^occasionally\b/i,
  /^(cumulative .+)$/i,
  /^(not be .+)$/i,
  /^(increase by .+)$/i,
  /^(stain .+)$/i,
  /^irrigate?\b/i,
  /^instil\b/i,
  /^applied\b/i,
  /^(Use .+)$/i,
  /^in water\b/i,
  /^(\d+-\d+\s*puffs of .+)$/i,
  /\binfusion\b/i,
  /(maintenance dose)(?:: )?/i,
  /\bmaintenance\b/i,
  /^(loading)$/i,
  /^(only vehicle for .+)$/i,
  /\bin each nostril\b/i,
  /\binto the ear\b/i,
  /\beach nostril\b/i,
  /\bin milk\b/i,
  /\bwith sterile water\b/i,
  /^(additional .+)$/i,
  /\/puff\b/i,
  /^(do not exceed .*)$/i,
  /\bsoak gauze\b/i,
  /after loading dose/i,
  /(loading dose)(?:: )?/i,
  /after each loose stool/i,
  /^(See.*)$/i,
  /^by weight band$/i,
  /^refer to STGs$/i,
  /(?:may need )?(repeat(?:ed)?(?:ing)? .*)/i,
  'volume depends on severity',
  /(can increase .*)$/i,
  'up to 6 times',
  'as early as possible in labour',
  'not sublingual',
  'with insulin',
  /until .*/i,
  'with Oxytocin',
  /preferably not on an empty stomach/i,
  'infused as fast as possible in one IV line',
  'immediately after birth routinely',
  /routinely to each eye after birth/i,
  /^if high risk,? .+$/i,
  /after expulsion is complete/i,
  /with or after a meal/i,
  /^followed .+/i,
  /^at hours?[-\s].+/i,
  /\bin patients\b.*/i,
  // /after .*/i,
  /\bcontinuous\b/i,
  /\binfused\b/i,
  /\bIV\b/,
  /\bslow\s*(?:IV\s*)?injection\b/i,
  /\bslow\b/i,
  'during the day',
  /after \d+ hours?/i,
  'after each feed',
  'after the procedure',
  /over \d+ seconds?/i,
  /^once$/i,
  /^range$/i,
  /for three weeks/i,
  /for two weeks/i,
  /\bday after methotrexate dose\b/i,
  /^total \d+ doses in \d+ days$/i,
  /^total doses = \d+ doses$/i,
  /^from \d+ days prior to .*/i,
  /^preoperatively$/i,
  /^surgery and .*/i,
  /^Add DTG\b.*/i,
  /^mixed with .*/i,
  /^impregnate .*/i,
  /^before administering .*/i,
  /^as per EPI schedule$/i,
  /^every minute$/i,
  /^Frequently$/i,
  /^Monday to Friday$/i,
  /^4 doses, see regimen$/i,
  /^at birth\b.*/i,
  /^\d+,\s*\d+\s*months$/i,
  /^\d+(?:,\s*\d+)+ weeks.*$/i,
  /^see regimen$/i,
  /^1g weekly$/i,
]
