// Auto-generated from ntasks.lisp
// Do not edit manually
import { parseWithSchema } from '../shared/s_expression.ts'
import { ntask } from '../shared/s_expression_schemas.ts'

function parseAsNTask(expr: string) {
  return parseWithSchema(expr, ntask)
}

export const NTASKS = [
  `(ntask "Check for Anaphylaxis" (ages adult) (any (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Itching" "finding")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Eruption" "morphologic abnormality")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Insect bite - wound" "disorder")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Swelling" "finding") (attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Face structure" "body structure"))) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Swelling" "finding") (attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Tongue structure" "body structure")))) (ncheck_for (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Itching" "finding")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Eruption" "morphologic abnormality")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Insect bite - wound" "disorder")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Swelling" "finding") (attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Face structure" "body structure"))) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Swelling" "finding") (attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Tongue structure" "body structure"))) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Dizziness" "finding")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Collapse" "finding")) (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Difficulty breathing" "finding")) (finding (snomed_concept "Exposure to (contextual qualifier)" "qualifier value") (snomed_concept "Peanut" "substance")) (finding (snomed_concept "Exposure to (contextual qualifier)" "qualifier value") (snomed_concept "Tree nut" "substance")) (finding (snomed_concept "Exposure to (contextual qualifier)" "qualifier value") (snomed_concept "Eggs (edible)" "substance")) (finding (snomed_concept "Exposure to (contextual qualifier)" "qualifier value") (snomed_concept "Milk" "substance")) (finding (snomed_concept "Exposure to (contextual qualifier)" "qualifier value") (snomed_concept "Fish" "substance"))) (diagnosis possible (snomed_concept "Anaphylaxis" "disorder")))`,
].map(parseAsNTask)
