FROM denoland/deno:2.7.5
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client && rm -rf /var/lib/apt/lists/*
RUN touch .env

COPY deno.lock ./
COPY deno.json ./
RUN deno install --allow-scripts

COPY db.d.ts ./
COPY db/ ./
COPY util/ ./
COPY shared/ ./

CMD ["sh", "-c", "deno task db:restore snomed && deno task db:migrate all"]