FROM denoland/deno:debian-2.3.5 as build

WORKDIR /app

# wkhtmltopdf install dependencies
RUN apt-get update && apt-get install -y \
        musl \
        libssl3 \
        ca-certificates \
        fontconfig \
        wget \
        libfreetype6 \
        libjpeg62-turbo \
        libpng16-16 \
        libssl3 \
        libx11-6 \
        libxcb1 \
        libxext6 \
        libxrender1 \
        xfonts-75dpi \
        xfonts-base \
        wkhtmltopdf

COPY ./ /app
RUN mkdir /app/temp_files
RUN chmod 755 /app/temp_files
RUN touch .env

# Test that wkhtmltopdf works
RUN wkhtmltopdf https://google.com temp_files/google.pdf

CMD ["deno", "task", "chatbot:pharmacist"]
