FROM node:20-slim
ENV NODE_ENV production
WORKDIR /usr/src/medplum
EXPOSE 8103

ADD ./medplum ./
RUN npm install
RUN npx turbo run build

ENTRYPOINT [ "node", "--require", "./packages/server/dist/otel/instrumentation.js", "packages/server/dist/index.js" ]
