FROM denoland/deno:2.7.5
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client && rm -rf /var/lib/apt/lists/*
RUN touch .env

COPY deno.lock ./
COPY deno.json ./
RUN deno install --allow-scripts

COPY ./ ./
