FROM denoland/deno:2.7.5
WORKDIR /app

COPY deno.json deno.lock ./
RUN deno install

COPY events ./events
COPY util ./util
COPY shared ./shared
COPY external-clients ./external-clients
COPY db/models ./db/models
COPY db/db.ts ./db/db.ts
COPY db/helpers.ts ./db/helpers.ts
COPY types.ts ./types.ts

RUN touch .env

CMD ["deno", "task", "events:processor"]
