// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_role_entrypoint_logout from './routes/[role_entrypoint]/logout.ts'
import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $app from './routes/app.tsx'
import * as $app_middleware from './routes/app/_middleware.tsx'
import * as $app_calendar from './routes/app/calendar.tsx'
import * as $app_calendar_appointments_appointment_id_media_media_id_ from './routes/app/calendar/appointments/[appointment_id]/media/[media_id].tsx'
import * as $app_calendar_appointments_id_ from './routes/app/calendar/appointments/[id].tsx'
import * as $app_calendar_appointments_schedule from './routes/app/calendar/appointments/schedule.tsx'
import * as $app_calendar_availability from './routes/app/calendar/availability.tsx'
import * as $app_chart from './routes/app/chart.tsx'
import * as $app_conditions from './routes/app/conditions.tsx'
import * as $app_consumables from './routes/app/consumables.tsx'
import * as $app_devices from './routes/app/devices.tsx'
import * as $app_drugs from './routes/app/drugs.tsx'
import * as $app_employees from './routes/app/employees.tsx'
import * as $app_icd10 from './routes/app/icd10.tsx'
import * as $app_icd10_search from './routes/app/icd10_search.tsx'
import * as $app_insufficient_permissions from './routes/app/insufficient_permissions.tsx'
import * as $app_manufactured_medications from './routes/app/manufactured_medications.tsx'
import * as $app_media_uuid_ from './routes/app/media/[uuid].tsx'
import * as $app_messaging from './routes/app/messaging.tsx'
import * as $app_messaging_threads_message_thread_id_ from './routes/app/messaging/threads/[message_thread_id].tsx'
import * as $app_organizations from './routes/app/organizations.tsx'
import * as $app_organizations_organization_id_ from './routes/app/organizations/[organization_id].tsx'
import * as $app_organizations_organization_id_middleware from './routes/app/organizations/[organization_id]/_middleware.ts'
import * as $app_organizations_organization_id_employees from './routes/app/organizations/[organization_id]/employees.tsx'
import * as $app_organizations_organization_id_employees_health_worker_id_ from './routes/app/organizations/[organization_id]/employees/[health_worker_id].tsx'
import * as $app_organizations_organization_id_employees_health_worker_id_approve from './routes/app/organizations/[organization_id]/employees/[health_worker_id]/approve.tsx'
import * as $app_organizations_organization_id_employees_health_worker_id_media_media_id_ from './routes/app/organizations/[organization_id]/employees/[health_worker_id]/media/[media_id].tsx'
import * as $app_organizations_organization_id_employees_invite from './routes/app/organizations/[organization_id]/employees/invite.tsx'
import * as $app_organizations_organization_id_inventory from './routes/app/organizations/[organization_id]/inventory.tsx'
import * as $app_organizations_organization_id_inventory_add_consumable from './routes/app/organizations/[organization_id]/inventory/add_consumable.tsx'
import * as $app_organizations_organization_id_inventory_add_device from './routes/app/organizations/[organization_id]/inventory/add_device.tsx'
import * as $app_organizations_organization_id_inventory_add_medicine from './routes/app/organizations/[organization_id]/inventory/add_medicine.tsx'
import * as $app_organizations_organization_id_inventory_add_procurer from './routes/app/organizations/[organization_id]/inventory/add_procurer.tsx'
import * as $app_organizations_organization_id_inventory_consume from './routes/app/organizations/[organization_id]/inventory/consume.tsx'
import * as $app_organizations_organization_id_inventory_history from './routes/app/organizations/[organization_id]/inventory/history.tsx'
import * as $app_organizations_organization_id_patients from './routes/app/organizations/[organization_id]/patients.tsx'
import * as $app_organizations_organization_id_patients_intake from './routes/app/organizations/[organization_id]/patients/intake.tsx'
import * as $app_organizations_organization_id_register from './routes/app/organizations/[organization_id]/register.tsx'
import * as $app_organizations_organization_id_register_step_ from './routes/app/organizations/[organization_id]/register/[step].tsx'
import * as $app_organizations_organization_id_waiting_room from './routes/app/organizations/[organization_id]/waiting_room.tsx'
import * as $app_organizations_organization_id_waiting_room_add from './routes/app/organizations/[organization_id]/waiting_room/add.tsx'
import * as $app_patients from './routes/app/patients.tsx'
import * as $app_patients_patient_id_ from './routes/app/patients/[patient_id].tsx'
import * as $app_patients_patient_id_middleware from './routes/app/patients/[patient_id]/_middleware.tsx'
import * as $app_patients_patient_id_avatar from './routes/app/patients/[patient_id]/avatar.tsx'
import * as $app_patients_patient_id_encounters from './routes/app/patients/[patient_id]/encounters.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_ from './routes/app/patients/[patient_id]/encounters/[encounter_id].tsx'
import * as $app_patients_patient_id_encounters_encounter_id_middleware from './routes/app/patients/[patient_id]/encounters/[encounter_id]/_middleware.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_clinical_notes from './routes/app/patients/[patient_id]/encounters/[encounter_id]/clinical_notes.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_close_visit from './routes/app/patients/[patient_id]/encounters/[encounter_id]/close_visit.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_diagnoses from './routes/app/patients/[patient_id]/encounters/[encounter_id]/diagnoses.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_diagnostic_tests from './routes/app/patients/[patient_id]/encounters/[encounter_id]/diagnostic_tests.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_examinations from './routes/app/patients/[patient_id]/encounters/[encounter_id]/examinations.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_head_to_toe_assessment from './routes/app/patients/[patient_id]/encounters/[encounter_id]/head_to_toe_assessment.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_orders from './routes/app/patients/[patient_id]/encounters/[encounter_id]/orders.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_prescriptions from './routes/app/patients/[patient_id]/encounters/[encounter_id]/prescriptions.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_referral from './routes/app/patients/[patient_id]/encounters/[encounter_id]/referral.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_symptoms from './routes/app/patients/[patient_id]/encounters/[encounter_id]/symptoms.tsx'
import * as $app_patients_patient_id_encounters_encounter_id_vitals from './routes/app/patients/[patient_id]/encounters/[encounter_id]/vitals.tsx'
import * as $app_patients_patient_id_profile_middleware from './routes/app/patients/[patient_id]/profile/_middleware.tsx'
import * as $app_patients_patient_id_profile_appointments from './routes/app/patients/[patient_id]/profile/appointments.tsx'
import * as $app_patients_patient_id_profile_history from './routes/app/patients/[patient_id]/profile/history.tsx'
import * as $app_patients_patient_id_profile_orders from './routes/app/patients/[patient_id]/profile/orders.tsx'
import * as $app_patients_patient_id_profile_profile from './routes/app/patients/[patient_id]/profile/profile.tsx'
import * as $app_patients_patient_id_profile_review from './routes/app/patients/[patient_id]/profile/review.tsx'
import * as $app_patients_patient_id_profile_summary from './routes/app/patients/[patient_id]/profile/summary.tsx'
import * as $app_patients_patient_id_profile_visits from './routes/app/patients/[patient_id]/profile/visits.tsx'
import * as $app_patients_patient_id_review from './routes/app/patients/[patient_id]/review.tsx'
import * as $app_patients_patient_id_review_middleware from './routes/app/patients/[patient_id]/review/_middleware.tsx'
import * as $app_patients_patient_id_review_clinical_notes from './routes/app/patients/[patient_id]/review/clinical_notes.tsx'
import * as $app_patients_patient_id_review_diagnosis from './routes/app/patients/[patient_id]/review/diagnosis.tsx'
import * as $app_patients_patient_id_review_orders from './routes/app/patients/[patient_id]/review/orders.tsx'
import * as $app_patients_patient_id_review_prescriptions from './routes/app/patients/[patient_id]/review/prescriptions.tsx'
import * as $app_patients_patient_id_review_referral from './routes/app/patients/[patient_id]/review/referral.tsx'
import * as $app_patients_patient_id_review_revert from './routes/app/patients/[patient_id]/review/revert.tsx'
import * as $app_pending_approval from './routes/app/pending_approval.tsx'
import * as $app_procurers from './routes/app/procurers.tsx'
import * as $app_providers from './routes/app/providers.tsx'
import * as $app_snomed_allergies from './routes/app/snomed/allergies.ts'
import * as $app_snomed_concepts from './routes/app/snomed/concepts.ts'
import * as $app_surgeries from './routes/app/surgeries.tsx'
import * as $app_symptoms from './routes/app/symptoms.tsx'
import * as $app_unauthorized from './routes/app/unauthorized.tsx'
import * as $apply from './routes/apply.tsx'
import * as $chatbot_incoming_whatsapp from './routes/chatbot/incoming-whatsapp.ts'
import * as $index from './routes/index.tsx'
import * as $interest from './routes/interest.tsx'
import * as $loading_test from './routes/loading-test.tsx'
import * as $logged_in from './routes/logged-in.tsx'
import * as $login from './routes/login.tsx'
import * as $partner from './routes/partner.tsx'
import * as $prescriptions_prescription_id_ from './routes/prescriptions/[prescription_id].tsx'
import * as $regulator from './routes/regulator.tsx'
import * as $regulator_middleware from './routes/regulator/_middleware.ts'
import * as $regulator_medicines from './routes/regulator/medicines.tsx'
import * as $regulator_medicines_medicine_id_recall from './routes/regulator/medicines/[medicine_id]/recall.tsx'
import * as $regulator_pharmacies from './routes/regulator/pharmacies.tsx'
import * as $regulator_pharmacies_pharmacy_name_ from './routes/regulator/pharmacies/[pharmacy.name].tsx'
import * as $regulator_pharmacies_pharmacy_id_ from './routes/regulator/pharmacies/[pharmacy_id].tsx'
import * as $regulator_pharmacies_add from './routes/regulator/pharmacies/add.tsx'
import * as $regulator_pharmacists from './routes/regulator/pharmacists.tsx'
import * as $regulator_pharmacists_pharmacist_id_ from './routes/regulator/pharmacists/[pharmacist_id].tsx'
import * as $regulator_pharmacists_pharmacist_id_edit from './routes/regulator/pharmacists/[pharmacist_id]/edit.tsx'
import * as $regulator_pharmacists_pharmacist_id_revoke from './routes/regulator/pharmacists/[pharmacist_id]/revoke.tsx'
import * as $regulator_pharmacists_invite from './routes/regulator/pharmacists/invite.tsx'
import * as $schedule_demo from './routes/schedule-demo.tsx'
import * as $volunteer from './routes/volunteer.tsx'
import * as $volunteer_role_ from './routes/volunteer/[role].tsx'
import * as $waitlist from './routes/waitlist.tsx'
import * as $AddConsumableSearch from './islands/AddConsumableSearch.tsx'
import * as $AddDeviceSearch from './islands/AddDeviceSearch.tsx'
import * as $AddPharmacistSearch from './islands/AddPharmacistSearch.tsx'
import * as $AddPharmacySearch from './islands/AddPharmacySearch.tsx'
import * as $AddRemove from './islands/AddRemove.tsx'
import * as $AddressForm from './islands/AddressForm.tsx'
import * as $AsyncSearch from './islands/AsyncSearch.tsx'
import * as $BackLink from './islands/BackLink.tsx'
import * as $BaseOption from './islands/BaseOption.tsx'
import * as $CloseButton from './islands/CloseButton.tsx'
import * as $ConditionSearch from './islands/ConditionSearch.tsx'
import * as $DemoVideo from './islands/DemoVideo.tsx'
import * as $ErrorListener from './islands/ErrorListener.tsx'
import * as $ErrorMessage from './islands/ErrorMessage.tsx'
import * as $FlyoutMenu from './islands/FlyoutMenu.tsx'
import * as $JobPost from './islands/JobPost.tsx'
import * as $LifestyleForm from './islands/LifestyleForm.tsx'
import * as $Menu from './islands/Menu.tsx'
import * as $NationalIdInput from './islands/NationalIdInput.tsx'
import * as $NationalIdInputCheckbox from './islands/NationalIdInputCheckbox.tsx'
import * as $NearestHealthCare from './islands/NearestHealthCare.tsx'
import * as $Notifications from './islands/Notifications.tsx'
import * as $Occupation0_18 from './islands/Occupation0-18.tsx'
import * as $Occupation19 from './islands/Occupation19.tsx'
import * as $OrganizationSearch from './islands/OrganizationSearch.tsx'
import * as $PersonSearch from './islands/PersonSearch.tsx'
import * as $ProvidersSelect from './islands/ProvidersSelect.tsx'
import * as $ReligionSelect from './islands/ReligionSelect.tsx'
import * as $Search from './islands/Search.tsx'
import * as $SelectWithOther from './islands/SelectWithOther.tsx'
import * as $SendTo_Button from './islands/SendTo/Button.tsx'
import * as $SendTo_Form from './islands/SendTo/Form.tsx'
import * as $SendTo_Header from './islands/SendTo/Header.tsx'
import * as $SendTo_Icons from './islands/SendTo/Icons.tsx'
import * as $SendTo_List from './islands/SendTo/List.tsx'
import * as $SendTo_ListItem from './islands/SendTo/ListItem.tsx'
import * as $SendTo_RequestRadioButtons from './islands/SendTo/RequestRadioButtons.tsx'
import * as $SendTo_SelectedPatient from './islands/SendTo/SelectedPatient.tsx'
import * as $SendTo_Sidebar from './islands/SendTo/Sidebar.tsx'
import * as $SparklinesExample from './islands/SparklinesExample.tsx'
import * as $SuccessMessage from './islands/SuccessMessage.tsx'
import * as $SurgerySearch from './islands/SurgerySearch.tsx'
import * as $WarningMessage from './islands/WarningMessage.tsx'
import * as $allergy_Input from './islands/allergy/Input.tsx'
import * as $allergy_Search from './islands/allergy/Search.tsx'
import * as $availability_form from './islands/availability-form.tsx'
import * as $diagnoses_Form from './islands/diagnoses/Form.tsx'
import * as $diagnoses_FormRow from './islands/diagnoses/FormRow.tsx'
import * as $drug_Input from './islands/drug/Input.tsx'
import * as $drug_Search from './islands/drug/Search.tsx'
import * as $examinations_BodySiteSelect from './islands/examinations/BodySiteSelect.tsx'
import * as $examinations_ChecklistItem from './islands/examinations/ChecklistItem.tsx'
import * as $examinations_Dialog from './islands/examinations/Dialog.tsx'
import * as $examinations_New from './islands/examinations/New.tsx'
import * as $family_Dependent from './islands/family/Dependent.tsx'
import * as $family_FamilyTypeSelect from './islands/family/FamilyTypeSelect.tsx'
import * as $family_Guardian from './islands/family/Guardian.tsx'
import * as $family_MaritalStatusSelect from './islands/family/MaritalStatusSelect.tsx'
import * as $family_NextOfKin from './islands/family/NextOfKin.tsx'
import * as $family_PatientCohabitationSelect from './islands/family/PatientCohabitationSelect.tsx'
import * as $family_RelationshipSelect from './islands/family/RelationshipSelect.tsx'
import * as $file_preview_input from './islands/file-preview-input.tsx'
import * as $form_Inputs from './islands/form/Inputs.tsx'
import * as $form_Listbox from './islands/form/Listbox.tsx'
import * as $form_buttons from './islands/form/buttons.tsx'
import * as $form_unsaved_changes_warning from './islands/form/unsaved_changes_warning.tsx'
import * as $icd10_SearchSpecific from './islands/icd10/SearchSpecific.tsx'
import * as $inventory_Consumable from './islands/inventory/Consumable.tsx'
import * as $inventory_ConsumeForm from './islands/inventory/ConsumeForm.tsx'
import * as $inventory_DeviceSearch from './islands/inventory/DeviceSearch.tsx'
import * as $inventory_ProcurerForm from './islands/inventory/ProcurerForm.tsx'
import * as $invites_form from './islands/invites-form.tsx'
import * as $landing_page_MHIDotsLogo from './islands/landing-page/MHIDotsLogo.tsx'
import * as $landing_page_NavBar from './islands/landing-page/NavBar.tsx'
import * as $lifestyle_AlcoholForm from './islands/lifestyle/AlcoholForm.tsx'
import * as $lifestyle_DietForm from './islands/lifestyle/DietForm.tsx'
import * as $lifestyle_ExerciseForm from './islands/lifestyle/ExerciseForm.tsx'
import * as $lifestyle_SexualActivityForm from './islands/lifestyle/SexualActivityForm.tsx'
import * as $lifestyle_SmokingForm from './islands/lifestyle/SmokingForm.tsx'
import * as $lifestyle_SubstanceUseForm from './islands/lifestyle/SubstanceUseForm.tsx'
import * as $major_surgeries_Form from './islands/major-surgeries/Form.tsx'
import * as $major_surgeries_Surgery from './islands/major-surgeries/Surgery.tsx'
import * as $manufactured_medication_Input from './islands/manufactured_medication/Input.tsx'
import * as $manufactured_medication_Search from './islands/manufactured_medication/Search.tsx'
import * as $medication_Input from './islands/medication/Input.tsx'
import * as $messages_ThreadList from './islands/messages/ThreadList.tsx'
import * as $nurse_registration_form from './islands/nurse-registration-form.tsx'
import * as $past_medical_conditions_Condition from './islands/past-medical-conditions/Condition.tsx'
import * as $past_medical_conditions_Form from './islands/past-medical-conditions/Form.tsx'
import * as $patient_cards from './islands/patient-cards.tsx'
import * as $patient_drawer_Drawer from './islands/patient-drawer/Drawer.tsx'
import * as $patient_drawer_FindingsList from './islands/patient-drawer/FindingsList.tsx'
import * as $patient_drawer_FindingsListItem from './islands/patient-drawer/FindingsListItem.tsx'
import * as $patient_drawer_FindingsListItemSchema from './islands/patient-drawer/FindingsListItemSchema.ts'
import * as $patient_drawer_VitalsList from './islands/patient-drawer/VitalsList.tsx'
import * as $patient_intake_AddressForm from './islands/patient-intake/AddressForm.tsx'
import * as $patient_intake_FamilyForm from './islands/patient-intake/FamilyForm.tsx'
import * as $patient_intake_IntakeForm from './islands/patient-intake/IntakeForm.tsx'
import * as $patient_intake_PersonalForm from './islands/patient-intake/PersonalForm.tsx'
import * as $pre_existing_conditions_Comorbidity from './islands/pre-existing-conditions/Comorbidity.tsx'
import * as $pre_existing_conditions_Condition from './islands/pre-existing-conditions/Condition.tsx'
import * as $pre_existing_conditions_Form from './islands/pre-existing-conditions/Form.tsx'
import * as $prescriptions_Form from './islands/prescriptions/Form.tsx'
import * as $prescriptions_MedicationInput from './islands/prescriptions/MedicationInput.tsx'
import * as $prescriptions_MedicationRow from './islands/prescriptions/MedicationRow.tsx'
import * as $prescriptions_ScheduleInput from './islands/prescriptions/ScheduleInput.tsx'
import * as $prescriptions_ScheduleRow from './islands/prescriptions/ScheduleRow.tsx'
import * as $referral_Form from './islands/referral/Form.tsx'
import * as $regulator_PharmacistForm from './islands/regulator/PharmacistForm.tsx'
import * as $regulator_PharmacyForm from './islands/regulator/PharmacyForm.tsx'
import * as $summary_DescriptionRow from './islands/summary/DescriptionRow.tsx'
import * as $symptoms_DurationInput from './islands/symptoms/DurationInput.tsx'
import * as $symptoms_Input from './islands/symptoms/Input.tsx'
import * as $symptoms_Section from './islands/symptoms/Section.tsx'
import * as $timer from './islands/timer.tsx'
import * as $useAsyncSearch from './islands/useAsyncSearch.tsx'
import * as $vitals_Form from './islands/vitals/Form.tsx'
import * as $vitals_VitalsFlag from './islands/vitals/VitalsFlag.tsx'
import * as $waiting_room_AddPatientForm from './islands/waiting_room/AddPatientForm.tsx'
import * as $waiting_room_AddPatientSearch from './islands/waiting_room/AddPatientSearch.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/[role_entrypoint]/logout.ts': $_role_entrypoint_logout,
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/app.tsx': $app,
    './routes/app/_middleware.tsx': $app_middleware,
    './routes/app/calendar.tsx': $app_calendar,
    './routes/app/calendar/appointments/[appointment_id]/media/[media_id].tsx':
      $app_calendar_appointments_appointment_id_media_media_id_,
    './routes/app/calendar/appointments/[id].tsx':
      $app_calendar_appointments_id_,
    './routes/app/calendar/appointments/schedule.tsx':
      $app_calendar_appointments_schedule,
    './routes/app/calendar/availability.tsx': $app_calendar_availability,
    './routes/app/chart.tsx': $app_chart,
    './routes/app/conditions.tsx': $app_conditions,
    './routes/app/consumables.tsx': $app_consumables,
    './routes/app/devices.tsx': $app_devices,
    './routes/app/drugs.tsx': $app_drugs,
    './routes/app/employees.tsx': $app_employees,
    './routes/app/icd10.tsx': $app_icd10,
    './routes/app/icd10_search.tsx': $app_icd10_search,
    './routes/app/insufficient_permissions.tsx': $app_insufficient_permissions,
    './routes/app/manufactured_medications.tsx': $app_manufactured_medications,
    './routes/app/media/[uuid].tsx': $app_media_uuid_,
    './routes/app/messaging.tsx': $app_messaging,
    './routes/app/messaging/threads/[message_thread_id].tsx':
      $app_messaging_threads_message_thread_id_,
    './routes/app/organizations.tsx': $app_organizations,
    './routes/app/organizations/[organization_id].tsx':
      $app_organizations_organization_id_,
    './routes/app/organizations/[organization_id]/_middleware.ts':
      $app_organizations_organization_id_middleware,
    './routes/app/organizations/[organization_id]/employees.tsx':
      $app_organizations_organization_id_employees,
    './routes/app/organizations/[organization_id]/employees/[health_worker_id].tsx':
      $app_organizations_organization_id_employees_health_worker_id_,
    './routes/app/organizations/[organization_id]/employees/[health_worker_id]/approve.tsx':
      $app_organizations_organization_id_employees_health_worker_id_approve,
    './routes/app/organizations/[organization_id]/employees/[health_worker_id]/media/[media_id].tsx':
      $app_organizations_organization_id_employees_health_worker_id_media_media_id_,
    './routes/app/organizations/[organization_id]/employees/invite.tsx':
      $app_organizations_organization_id_employees_invite,
    './routes/app/organizations/[organization_id]/inventory.tsx':
      $app_organizations_organization_id_inventory,
    './routes/app/organizations/[organization_id]/inventory/add_consumable.tsx':
      $app_organizations_organization_id_inventory_add_consumable,
    './routes/app/organizations/[organization_id]/inventory/add_device.tsx':
      $app_organizations_organization_id_inventory_add_device,
    './routes/app/organizations/[organization_id]/inventory/add_medicine.tsx':
      $app_organizations_organization_id_inventory_add_medicine,
    './routes/app/organizations/[organization_id]/inventory/add_procurer.tsx':
      $app_organizations_organization_id_inventory_add_procurer,
    './routes/app/organizations/[organization_id]/inventory/consume.tsx':
      $app_organizations_organization_id_inventory_consume,
    './routes/app/organizations/[organization_id]/inventory/history.tsx':
      $app_organizations_organization_id_inventory_history,
    './routes/app/organizations/[organization_id]/patients.tsx':
      $app_organizations_organization_id_patients,
    './routes/app/organizations/[organization_id]/patients/intake.tsx':
      $app_organizations_organization_id_patients_intake,
    './routes/app/organizations/[organization_id]/register.tsx':
      $app_organizations_organization_id_register,
    './routes/app/organizations/[organization_id]/register/[step].tsx':
      $app_organizations_organization_id_register_step_,
    './routes/app/organizations/[organization_id]/waiting_room.tsx':
      $app_organizations_organization_id_waiting_room,
    './routes/app/organizations/[organization_id]/waiting_room/add.tsx':
      $app_organizations_organization_id_waiting_room_add,
    './routes/app/patients.tsx': $app_patients,
    './routes/app/patients/[patient_id].tsx': $app_patients_patient_id_,
    './routes/app/patients/[patient_id]/_middleware.tsx':
      $app_patients_patient_id_middleware,
    './routes/app/patients/[patient_id]/avatar.tsx':
      $app_patients_patient_id_avatar,
    './routes/app/patients/[patient_id]/encounters.tsx':
      $app_patients_patient_id_encounters,
    './routes/app/patients/[patient_id]/encounters/[encounter_id].tsx':
      $app_patients_patient_id_encounters_encounter_id_,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/_middleware.tsx':
      $app_patients_patient_id_encounters_encounter_id_middleware,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/clinical_notes.tsx':
      $app_patients_patient_id_encounters_encounter_id_clinical_notes,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/close_visit.tsx':
      $app_patients_patient_id_encounters_encounter_id_close_visit,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/diagnoses.tsx':
      $app_patients_patient_id_encounters_encounter_id_diagnoses,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/diagnostic_tests.tsx':
      $app_patients_patient_id_encounters_encounter_id_diagnostic_tests,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/examinations.tsx':
      $app_patients_patient_id_encounters_encounter_id_examinations,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/head_to_toe_assessment.tsx':
      $app_patients_patient_id_encounters_encounter_id_head_to_toe_assessment,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/orders.tsx':
      $app_patients_patient_id_encounters_encounter_id_orders,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/prescriptions.tsx':
      $app_patients_patient_id_encounters_encounter_id_prescriptions,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/referral.tsx':
      $app_patients_patient_id_encounters_encounter_id_referral,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/symptoms.tsx':
      $app_patients_patient_id_encounters_encounter_id_symptoms,
    './routes/app/patients/[patient_id]/encounters/[encounter_id]/vitals.tsx':
      $app_patients_patient_id_encounters_encounter_id_vitals,
    './routes/app/patients/[patient_id]/profile/_middleware.tsx':
      $app_patients_patient_id_profile_middleware,
    './routes/app/patients/[patient_id]/profile/appointments.tsx':
      $app_patients_patient_id_profile_appointments,
    './routes/app/patients/[patient_id]/profile/history.tsx':
      $app_patients_patient_id_profile_history,
    './routes/app/patients/[patient_id]/profile/orders.tsx':
      $app_patients_patient_id_profile_orders,
    './routes/app/patients/[patient_id]/profile/profile.tsx':
      $app_patients_patient_id_profile_profile,
    './routes/app/patients/[patient_id]/profile/review.tsx':
      $app_patients_patient_id_profile_review,
    './routes/app/patients/[patient_id]/profile/summary.tsx':
      $app_patients_patient_id_profile_summary,
    './routes/app/patients/[patient_id]/profile/visits.tsx':
      $app_patients_patient_id_profile_visits,
    './routes/app/patients/[patient_id]/review.tsx':
      $app_patients_patient_id_review,
    './routes/app/patients/[patient_id]/review/_middleware.tsx':
      $app_patients_patient_id_review_middleware,
    './routes/app/patients/[patient_id]/review/clinical_notes.tsx':
      $app_patients_patient_id_review_clinical_notes,
    './routes/app/patients/[patient_id]/review/diagnosis.tsx':
      $app_patients_patient_id_review_diagnosis,
    './routes/app/patients/[patient_id]/review/orders.tsx':
      $app_patients_patient_id_review_orders,
    './routes/app/patients/[patient_id]/review/prescriptions.tsx':
      $app_patients_patient_id_review_prescriptions,
    './routes/app/patients/[patient_id]/review/referral.tsx':
      $app_patients_patient_id_review_referral,
    './routes/app/patients/[patient_id]/review/revert.tsx':
      $app_patients_patient_id_review_revert,
    './routes/app/pending_approval.tsx': $app_pending_approval,
    './routes/app/procurers.tsx': $app_procurers,
    './routes/app/providers.tsx': $app_providers,
    './routes/app/snomed/allergies.ts': $app_snomed_allergies,
    './routes/app/snomed/concepts.ts': $app_snomed_concepts,
    './routes/app/surgeries.tsx': $app_surgeries,
    './routes/app/symptoms.tsx': $app_symptoms,
    './routes/app/unauthorized.tsx': $app_unauthorized,
    './routes/apply.tsx': $apply,
    './routes/chatbot/incoming-whatsapp.ts': $chatbot_incoming_whatsapp,
    './routes/index.tsx': $index,
    './routes/interest.tsx': $interest,
    './routes/loading-test.tsx': $loading_test,
    './routes/logged-in.tsx': $logged_in,
    './routes/login.tsx': $login,
    './routes/partner.tsx': $partner,
    './routes/prescriptions/[prescription_id].tsx':
      $prescriptions_prescription_id_,
    './routes/regulator.tsx': $regulator,
    './routes/regulator/_middleware.ts': $regulator_middleware,
    './routes/regulator/medicines.tsx': $regulator_medicines,
    './routes/regulator/medicines/[medicine_id]/recall.tsx':
      $regulator_medicines_medicine_id_recall,
    './routes/regulator/pharmacies.tsx': $regulator_pharmacies,
    './routes/regulator/pharmacies/[pharmacy.name].tsx':
      $regulator_pharmacies_pharmacy_name_,
    './routes/regulator/pharmacies/[pharmacy_id].tsx':
      $regulator_pharmacies_pharmacy_id_,
    './routes/regulator/pharmacies/add.tsx': $regulator_pharmacies_add,
    './routes/regulator/pharmacists.tsx': $regulator_pharmacists,
    './routes/regulator/pharmacists/[pharmacist_id].tsx':
      $regulator_pharmacists_pharmacist_id_,
    './routes/regulator/pharmacists/[pharmacist_id]/edit.tsx':
      $regulator_pharmacists_pharmacist_id_edit,
    './routes/regulator/pharmacists/[pharmacist_id]/revoke.tsx':
      $regulator_pharmacists_pharmacist_id_revoke,
    './routes/regulator/pharmacists/invite.tsx': $regulator_pharmacists_invite,
    './routes/schedule-demo.tsx': $schedule_demo,
    './routes/volunteer.tsx': $volunteer,
    './routes/volunteer/[role].tsx': $volunteer_role_,
    './routes/waitlist.tsx': $waitlist,
  },
  islands: {
    './islands/AddConsumableSearch.tsx': $AddConsumableSearch,
    './islands/AddDeviceSearch.tsx': $AddDeviceSearch,
    './islands/AddPharmacistSearch.tsx': $AddPharmacistSearch,
    './islands/AddPharmacySearch.tsx': $AddPharmacySearch,
    './islands/AddRemove.tsx': $AddRemove,
    './islands/AddressForm.tsx': $AddressForm,
    './islands/AsyncSearch.tsx': $AsyncSearch,
    './islands/BackLink.tsx': $BackLink,
    './islands/BaseOption.tsx': $BaseOption,
    './islands/CloseButton.tsx': $CloseButton,
    './islands/ConditionSearch.tsx': $ConditionSearch,
    './islands/DemoVideo.tsx': $DemoVideo,
    './islands/ErrorListener.tsx': $ErrorListener,
    './islands/ErrorMessage.tsx': $ErrorMessage,
    './islands/FlyoutMenu.tsx': $FlyoutMenu,
    './islands/JobPost.tsx': $JobPost,
    './islands/LifestyleForm.tsx': $LifestyleForm,
    './islands/Menu.tsx': $Menu,
    './islands/NationalIdInput.tsx': $NationalIdInput,
    './islands/NationalIdInputCheckbox.tsx': $NationalIdInputCheckbox,
    './islands/NearestHealthCare.tsx': $NearestHealthCare,
    './islands/Notifications.tsx': $Notifications,
    './islands/Occupation0-18.tsx': $Occupation0_18,
    './islands/Occupation19.tsx': $Occupation19,
    './islands/OrganizationSearch.tsx': $OrganizationSearch,
    './islands/PersonSearch.tsx': $PersonSearch,
    './islands/ProvidersSelect.tsx': $ProvidersSelect,
    './islands/ReligionSelect.tsx': $ReligionSelect,
    './islands/Search.tsx': $Search,
    './islands/SelectWithOther.tsx': $SelectWithOther,
    './islands/SendTo/Button.tsx': $SendTo_Button,
    './islands/SendTo/Form.tsx': $SendTo_Form,
    './islands/SendTo/Header.tsx': $SendTo_Header,
    './islands/SendTo/Icons.tsx': $SendTo_Icons,
    './islands/SendTo/List.tsx': $SendTo_List,
    './islands/SendTo/ListItem.tsx': $SendTo_ListItem,
    './islands/SendTo/RequestRadioButtons.tsx': $SendTo_RequestRadioButtons,
    './islands/SendTo/SelectedPatient.tsx': $SendTo_SelectedPatient,
    './islands/SendTo/Sidebar.tsx': $SendTo_Sidebar,
    './islands/SparklinesExample.tsx': $SparklinesExample,
    './islands/SuccessMessage.tsx': $SuccessMessage,
    './islands/SurgerySearch.tsx': $SurgerySearch,
    './islands/WarningMessage.tsx': $WarningMessage,
    './islands/allergy/Input.tsx': $allergy_Input,
    './islands/allergy/Search.tsx': $allergy_Search,
    './islands/availability-form.tsx': $availability_form,
    './islands/diagnoses/Form.tsx': $diagnoses_Form,
    './islands/diagnoses/FormRow.tsx': $diagnoses_FormRow,
    './islands/drug/Input.tsx': $drug_Input,
    './islands/drug/Search.tsx': $drug_Search,
    './islands/examinations/BodySiteSelect.tsx': $examinations_BodySiteSelect,
    './islands/examinations/ChecklistItem.tsx': $examinations_ChecklistItem,
    './islands/examinations/Dialog.tsx': $examinations_Dialog,
    './islands/examinations/New.tsx': $examinations_New,
    './islands/family/Dependent.tsx': $family_Dependent,
    './islands/family/FamilyTypeSelect.tsx': $family_FamilyTypeSelect,
    './islands/family/Guardian.tsx': $family_Guardian,
    './islands/family/MaritalStatusSelect.tsx': $family_MaritalStatusSelect,
    './islands/family/NextOfKin.tsx': $family_NextOfKin,
    './islands/family/PatientCohabitationSelect.tsx':
      $family_PatientCohabitationSelect,
    './islands/family/RelationshipSelect.tsx': $family_RelationshipSelect,
    './islands/file-preview-input.tsx': $file_preview_input,
    './islands/form/Inputs.tsx': $form_Inputs,
    './islands/form/Listbox.tsx': $form_Listbox,
    './islands/form/buttons.tsx': $form_buttons,
    './islands/form/unsaved_changes_warning.tsx': $form_unsaved_changes_warning,
    './islands/icd10/SearchSpecific.tsx': $icd10_SearchSpecific,
    './islands/inventory/Consumable.tsx': $inventory_Consumable,
    './islands/inventory/ConsumeForm.tsx': $inventory_ConsumeForm,
    './islands/inventory/DeviceSearch.tsx': $inventory_DeviceSearch,
    './islands/inventory/ProcurerForm.tsx': $inventory_ProcurerForm,
    './islands/invites-form.tsx': $invites_form,
    './islands/landing-page/MHIDotsLogo.tsx': $landing_page_MHIDotsLogo,
    './islands/landing-page/NavBar.tsx': $landing_page_NavBar,
    './islands/lifestyle/AlcoholForm.tsx': $lifestyle_AlcoholForm,
    './islands/lifestyle/DietForm.tsx': $lifestyle_DietForm,
    './islands/lifestyle/ExerciseForm.tsx': $lifestyle_ExerciseForm,
    './islands/lifestyle/SexualActivityForm.tsx': $lifestyle_SexualActivityForm,
    './islands/lifestyle/SmokingForm.tsx': $lifestyle_SmokingForm,
    './islands/lifestyle/SubstanceUseForm.tsx': $lifestyle_SubstanceUseForm,
    './islands/major-surgeries/Form.tsx': $major_surgeries_Form,
    './islands/major-surgeries/Surgery.tsx': $major_surgeries_Surgery,
    './islands/manufactured_medication/Input.tsx':
      $manufactured_medication_Input,
    './islands/manufactured_medication/Search.tsx':
      $manufactured_medication_Search,
    './islands/medication/Input.tsx': $medication_Input,
    './islands/messages/ThreadList.tsx': $messages_ThreadList,
    './islands/nurse-registration-form.tsx': $nurse_registration_form,
    './islands/past-medical-conditions/Condition.tsx':
      $past_medical_conditions_Condition,
    './islands/past-medical-conditions/Form.tsx': $past_medical_conditions_Form,
    './islands/patient-cards.tsx': $patient_cards,
    './islands/patient-drawer/Drawer.tsx': $patient_drawer_Drawer,
    './islands/patient-drawer/FindingsList.tsx': $patient_drawer_FindingsList,
    './islands/patient-drawer/FindingsListItem.tsx':
      $patient_drawer_FindingsListItem,
    './islands/patient-drawer/FindingsListItemSchema.ts':
      $patient_drawer_FindingsListItemSchema,
    './islands/patient-drawer/VitalsList.tsx': $patient_drawer_VitalsList,
    './islands/patient-intake/AddressForm.tsx': $patient_intake_AddressForm,
    './islands/patient-intake/FamilyForm.tsx': $patient_intake_FamilyForm,
    './islands/patient-intake/IntakeForm.tsx': $patient_intake_IntakeForm,
    './islands/patient-intake/PersonalForm.tsx': $patient_intake_PersonalForm,
    './islands/pre-existing-conditions/Comorbidity.tsx':
      $pre_existing_conditions_Comorbidity,
    './islands/pre-existing-conditions/Condition.tsx':
      $pre_existing_conditions_Condition,
    './islands/pre-existing-conditions/Form.tsx': $pre_existing_conditions_Form,
    './islands/prescriptions/Form.tsx': $prescriptions_Form,
    './islands/prescriptions/MedicationInput.tsx':
      $prescriptions_MedicationInput,
    './islands/prescriptions/MedicationRow.tsx': $prescriptions_MedicationRow,
    './islands/prescriptions/ScheduleInput.tsx': $prescriptions_ScheduleInput,
    './islands/prescriptions/ScheduleRow.tsx': $prescriptions_ScheduleRow,
    './islands/referral/Form.tsx': $referral_Form,
    './islands/regulator/PharmacistForm.tsx': $regulator_PharmacistForm,
    './islands/regulator/PharmacyForm.tsx': $regulator_PharmacyForm,
    './islands/summary/DescriptionRow.tsx': $summary_DescriptionRow,
    './islands/symptoms/DurationInput.tsx': $symptoms_DurationInput,
    './islands/symptoms/Input.tsx': $symptoms_Input,
    './islands/symptoms/Section.tsx': $symptoms_Section,
    './islands/timer.tsx': $timer,
    './islands/useAsyncSearch.tsx': $useAsyncSearch,
    './islands/vitals/Form.tsx': $vitals_Form,
    './islands/vitals/VitalsFlag.tsx': $vitals_VitalsFlag,
    './islands/waiting_room/AddPatientForm.tsx': $waiting_room_AddPatientForm,
    './islands/waiting_room/AddPatientSearch.tsx':
      $waiting_room_AddPatientSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
