import { assertEquals } from 'std/assert/assert_equals.ts'
import { describe, it } from 'std/testing/bdd.ts'
import { KEYED_WARNING_SIGNS } from '../../shared/warning_signs.ts'
import { parseExpression } from '../../shared/s_expression.ts'

describe('shared/warning_signs.ts', () => {
  describe('parsing signs', () => {
    it('works', () => {
      const warning_signs = []
      for (
        const {
          clinical_finding_s_expression,
          prompt_when_s_expression,
          ...sign
        } of KEYED_WARNING_SIGNS
      ) {
        try {
          warning_signs.push({
            ...sign,
            clinical_finding: parseExpression(clinical_finding_s_expression),
            prompt_when: prompt_when_s_expression
              ? parseExpression(prompt_when_s_expression)
              : null,
          })
        } catch (err) {
          console.log(sign)
          throw err
        }
      }

      assertEquals(warning_signs, [
        {
          'key': 'Obstructed airway',
          'sats_primary_name': 'Obstructed airway',
          'sats_secondary_text': 'Not breathing',
          'sats_priority': 'Emergency',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Respiratory obstruction',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Seizure',
          'sats_primary_name': 'Seizure',
          'sats_secondary_text': 'Current',
          'sats_priority': 'Emergency',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Seizure',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [
              {
                'atom': 'qualifier',
                'specific_snomed_concept': {
                  'atom': 'snomed_concept',
                  'name': 'Current',
                  'category': 'qualifier value',
                  'type': 'snomed_concept_name_and_category',
                },
                'qualifiers': [],
              },
            ],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Burn Facial',
          'sats_primary_name': 'Burn',
          'sats_secondary_text': 'Facial',
          'sats_priority': 'Emergency',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Burn of face',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Burn Inhalation',
          'sats_primary_name': 'Burn',
          'sats_secondary_text': 'Inhalation',
          'sats_priority': 'Emergency',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Inhalation burn due to hot gas',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Cardiac arrest',
          'sats_primary_name': 'Cardiac arrest',
          'sats_secondary_text': null,
          'sats_priority': 'Emergency',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Cardiac arrest',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'High energy transfer',
          'sats_primary_name': 'High energy transfer',
          'sats_secondary_text': 'Severe mechanism of injury',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Injury caused by causative force',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Focal neurology — acute',
          'sats_primary_name': 'Focal neurology — acute',
          'sats_secondary_text': 'Stroke',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Cerebrovascular accident',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Burn Circumferential',
          'sats_primary_name': 'Burn',
          'sats_secondary_text': 'Circumferential',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Burn',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [
              {
                'atom': 'qualifier',
                'specific_snomed_concept': {
                  'atom': 'snomed_concept',
                  'name': 'Circumferential',
                  'category': 'qualifier value',
                  'type': 'snomed_concept_name_and_category',
                },
                'qualifiers': [],
              },
            ],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Shortness of breath - acute',
          'sats_primary_name': 'Shortness of breath - acute',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Dyspnea',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [
              {
                'atom': 'qualifier',
                'specific_snomed_concept': {
                  'atom': 'snomed_concept',
                  'name': 'Severe (severity modifier)',
                  'category': 'qualifier value',
                  'type': 'snomed_concept_name_and_category',
                },
                'qualifiers': [],
              },
            ],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Aggression',
          'sats_primary_name': 'Aggression',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Aggressive behavior',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Burn Chemical',
          'sats_primary_name': 'Burn',
          'sats_secondary_text': 'Chemical',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Chemical burn',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Threatened limb',
          'sats_primary_name': 'Threatened limb',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Limb ischemia',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Poisoning',
          'excluding_s_expression':
            '(finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Overdose" "disorder"))',
          'sats_primary_name': 'Poisoning',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Poisoning',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Overdose',
          'sats_primary_name': 'Overdose',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Overdose',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Coughing blood',
          'sats_primary_name': 'Coughing blood',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Hemoptysis',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Eye injury',
          'sats_primary_name': 'Eye injury',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Injury of globe of eye',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Chest pain',
          'sats_primary_name': 'Chest pain',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Chest pain',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Dislocation of larger joint',
          'excluding_s_expression':
            '\n      (or (finding (snomed_concept "Finding site" "attribute") (snomed_concept "Finger structure" "body structure"))\n           (finding (snomed_concept "Finding site" "attribute") (snomed_concept "Toe structure" "body structure")))\n    ',
          'sats_primary_name': 'Dislocation of larger joint',
          'sats_secondary_text': 'not finger or toe',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Dislocation',
              'category': 'morphologic abnormality',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Vomiting fresh blood',
          'sats_primary_name': 'Vomiting fresh blood',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Vomiting blood - fresh',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Stabbed neck',
          'sats_primary_name': 'Stabbed neck',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Stab wound of neck',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Fractured - compound',
          'sats_primary_name': 'Fractured - compound',
          'sats_secondary_text': 'with a break in skin',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Fracture, open',
              'category': 'morphologic abnormality',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Pregnancy and abdominal trauma',
          'sats_primary_name': 'Pregnancy and abdominal trauma',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Traumatic injury',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': {
            'atom': 'active_condition',
            'snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Pregnancy',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
          },
        },
        {
          'key': 'Pregnancy and abdominal pain',
          'sats_primary_name': 'Pregnancy and abdominal pain',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Abdominal pain',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': {
            'atom': 'active_condition',
            'snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Pregnancy',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
          },
        },
        {
          'key': 'Hemorrhage Uncontrolled',
          'sats_primary_name': 'Hemorrhage Uncontrolled',
          'sats_secondary_text': 'arterial bleed',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Bleeding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [
              {
                'atom': 'qualifier',
                'specific_snomed_concept': {
                  'atom': 'snomed_concept',
                  'name': 'Uncontrolled',
                  'category': 'qualifier value',
                  'type': 'snomed_concept_name_and_category',
                },
                'qualifiers': [],
              },
            ],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Seizure - post ictal',
          'sats_primary_name': 'Seizure - post ictal',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Post-ictal state',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Severe pain',
          'sats_primary_name': 'Severe pain',
          'sats_secondary_text': null,
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Severe pain',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Burn Moderate severity',
          'sats_primary_name': 'Burn',
          'sats_secondary_text': 'Moderate severity',
          'sats_priority': 'Very urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Laceration of hand',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [
              {
                'atom': 'qualifier',
                'specific_snomed_concept': {
                  'atom': 'snomed_concept',
                  'name': 'Moderate (severity modifier)',
                  'category': 'qualifier value',
                  'type': 'snomed_concept_name_and_category',
                },
                'qualifiers': [],
              },
            ],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Haemorrhage Controlled',
          'sats_primary_name': 'Haemorrhage',
          'sats_secondary_text': 'Controlled',
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Bleeding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [
              {
                'atom': 'qualifier',
                'specific_snomed_concept': {
                  'atom': 'snomed_concept',
                  'name': 'Controlled',
                  'category': 'qualifier value',
                  'type': 'snomed_concept_name_and_category',
                },
                'qualifiers': [],
              },
            ],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Dislocation of finger',
          'sats_primary_name': 'Dislocation of finger',
          'sats_secondary_text': null,
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Dislocation of digit of hand',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Dislocation of toe joint',
          'sats_primary_name': 'Dislocation of toe joint',
          'sats_secondary_text': null,
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Dislocation of toe joint',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Fracture',
          'sats_primary_name': 'Fracture',
          'sats_secondary_text': 'Closed (no break in the skin)',
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Closed fracture of bone',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Burn Other',
          'excluding_s_expression':
            '\n      (or\n        (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Burn" "disorder") (qualifier (snomed_concept "Circumferential" "qualifier value")))\n        (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Inhalation burn due to hot gas" "disorder"))\n        (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Chemical burn" "disorder"))\n        (finding (snomed_concept "Clinical finding" "finding") (snomed_concept "Burn of face" "disorder")))\n    ',
          'sats_primary_name': 'Burn',
          'sats_secondary_text': 'Other',
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Burn',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Abdominal pain',
          'sats_primary_name': 'Abdominal pain',
          'sats_secondary_text': null,
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Abdominal pain',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': {
            'atom': 'not',
            'expression': {
              'atom': 'active_condition',
              'snomed_concept': {
                'atom': 'snomed_concept',
                'name': 'Pregnancy',
                'category': 'finding',
                'type': 'snomed_concept_name_and_category',
              },
            },
          },
        },
        {
          'key': 'Persistent vomiting',
          'sats_primary_name': 'Persistent vomiting',
          'sats_secondary_text': null,
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Persistent vomiting',
              'category': 'disorder',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
        {
          'key': 'Moderate pain',
          'sats_primary_name': 'Moderate pain',
          'sats_secondary_text': null,
          'sats_priority': 'Urgent',
          'clinical_finding': {
            'atom': 'finding',
            'root_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Clinical finding',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'specific_snomed_concept': {
              'atom': 'snomed_concept',
              'name': 'Moderate pain',
              'category': 'finding',
              'type': 'snomed_concept_name_and_category',
            },
            'value_snomed_concept': null,
            'qualifiers': [],
            'attributes': [],
            'exact': false,
          },
          'prompt_when': null,
        },
      ])
    })
  })
})
