export const allAllergies = [
  'Wheat',
  'Cereals',
  'Celery',
  'Carrots',
  'Potatoes',
  'Eggs',
  'Fish',
  'Melon',
  'Mangos',
  'Pawpaws',
  'Pineapples',
  'Strawberries',
  'Apples',
  'Bananas',
  'Avocados',
  'Garlic',
  'Oats',
  'Maize',
  'Milk',
  'Butter',
  'Cheese',
  'Cream/ Sour Cream',
  'Yogurt',
  'Custard',
  'Ice cream',
  'Pudding',
  'Peanuts',
  'Poultry Meat',
  'Red Meat',
  'Rice',
  'Shellfish',
  'Soya beans',
  'Preservatives',
  'Hayfever',
  'Asthma',
  'Eczema',
  'Tetracycline',
  'Carbamazepine',
  'Penicillins',
  'Cephalosporins',
  'Sulfonamides',
  'Non-steroidal anti-inflammatory drugs',
  'Contrast dye',
  'Local anaesthetics',
  'Pollen',
  'Grass Trees',
  'Cats',
  'Dogs',
  'Insect sting',
  'Poison Ivy',
  'Mold',
  'Perfume',
  'Cosmetics',
  'Semen',
  'Water',
  'Latex',
  'Cold stimuli',
  'House dust mites',
  'Gold',
  'Nickel',
  'Chromium',
  'Cobalt chloride',
  'Formaldehye',
  'Photographic developers',
  'Fungicide',
  'Liquid soap',
  'Shampoos',
  'Latex',
  'Hair dyes',
  'Colour developers',
  'Body paints/ Henna',
  'Nail polish',
  'Swimming gear',
  'Cotton',
  'Wool',
  'Synthetics',
]
