#! /usr/bin/env bash
set -euo pipefail

# My hypothesis is that limiting the number of tables speeds up typescript's type checking.
# So with this we'll need to add to the list of tables we're using in the codebase.
MEDPLUM_TABLES_IN_USE=(
  Address
  Organization
  Location
  Media
  Encounter
  Condition
  ConditionEvidence
  ProjectMembership
  ClientApplication
  Project
  Practitioner
)

MEDPLUM_TABLES=(
  AccessPolicy
  AccessPolicy_History
  AccessPolicy_References
  AccessPolicy_Token
  Account
  Account_History
  Account_References
  Account_Token
  ActivityDefinition
  ActivityDefinition_History
  ActivityDefinition_References
  ActivityDefinition_Token
  Address
  AdverseEvent
  AdverseEvent_History
  AdverseEvent_References
  AdverseEvent_Token
  Agent
  Agent_History
  Agent_References
  Agent_Token
  AllergyIntolerance
  AllergyIntolerance_History
  AllergyIntolerance_References
  AllergyIntolerance_Token
  Appointment
  Appointment_History
  Appointment_References
  Appointment_Token
  AppointmentResponse
  AppointmentResponse_History
  AppointmentResponse_References
  AppointmentResponse_Token
  AsyncJob
  AsyncJob_History
  AsyncJob_References
  AsyncJob_Token
  AuditEvent
  AuditEvent_History
  AuditEvent_References
  AuditEvent_Token
  Basic
  Basic_History
  Basic_References
  Basic_Token
  Binary
  Binary_History
  Binary_References
  Binary_Token
  BiologicallyDerivedProduct
  BiologicallyDerivedProduct_History
  BiologicallyDerivedProduct_References
  BiologicallyDerivedProduct_Token
  BodyStructure
  BodyStructure_History
  BodyStructure_References
  BodyStructure_Token
  Bot
  Bot_History
  Bot_References
  Bot_Token
  BulkDataExport
  BulkDataExport_History
  BulkDataExport_References
  BulkDataExport_Token
  Bundle
  Bundle_History
  Bundle_References
  Bundle_Token
  CapabilityStatement
  CapabilityStatement_History
  CapabilityStatement_References
  CapabilityStatement_Token
  CarePlan
  CarePlan_History
  CarePlan_References
  CarePlan_Token
  CareTeam
  CareTeam_History
  CareTeam_References
  CareTeam_Token
  CatalogEntry
  CatalogEntry_History
  CatalogEntry_References
  CatalogEntry_Token
  ChargeItem
  ChargeItem_History
  ChargeItem_References
  ChargeItem_Token
  ChargeItemDefinition
  ChargeItemDefinition_History
  ChargeItemDefinition_References
  ChargeItemDefinition_Token
  Claim
  Claim_History
  Claim_References
  Claim_Token
  ClaimResponse
  ClaimResponse_History
  ClaimResponse_References
  ClaimResponse_Token
  ClientApplication
  ClientApplication_History
  ClientApplication_References
  ClientApplication_Token
  ClinicalImpression
  ClinicalImpression_History
  ClinicalImpression_References
  ClinicalImpression_Token
  CodeSystem
  CodeSystem_History
  CodeSystem_Property
  CodeSystem_References
  CodeSystem_Token
  Coding
  Coding_Property
  Communication
  Communication_History
  Communication_References
  Communication_Token
  CommunicationRequest
  CommunicationRequest_History
  CommunicationRequest_References
  CommunicationRequest_Token
  CompartmentDefinition
  CompartmentDefinition_History
  CompartmentDefinition_References
  CompartmentDefinition_Token
  Composition
  Composition_History
  Composition_References
  Composition_Token
  ConceptMap
  ConceptMap_History
  ConceptMap_References
  ConceptMap_Token
  Condition
  Condition_History
  Condition_References
  Condition_Token
  Consent
  Consent_History
  Consent_References
  Consent_Token
  ContactPoint
  Contract
  Contract_History
  Contract_References
  Contract_Token
  Coverage
  Coverage_History
  Coverage_References
  Coverage_Token
  CoverageEligibilityRequest
  CoverageEligibilityRequest_History
  CoverageEligibilityRequest_References
  CoverageEligibilityRequest_Token
  CoverageEligibilityResponse
  CoverageEligibilityResponse_History
  CoverageEligibilityResponse_References
  CoverageEligibilityResponse_Token
  DatabaseMigration
  DetectedIssue
  DetectedIssue_History
  DetectedIssue_References
  DetectedIssue_Token
  Device
  Device_History
  Device_References
  Device_Token
  DeviceDefinition
  DeviceDefinition_History
  DeviceDefinition_References
  DeviceDefinition_Token
  DeviceMetric
  DeviceMetric_History
  DeviceMetric_References
  DeviceMetric_Token
  DeviceRequest
  DeviceRequest_History
  DeviceRequest_References
  DeviceRequest_Token
  DeviceUseStatement
  DeviceUseStatement_History
  DeviceUseStatement_References
  DeviceUseStatement_Token
  DiagnosticReport
  DiagnosticReport_History
  DiagnosticReport_References
  DiagnosticReport_Token
  DocumentManifest
  DocumentManifest_History
  DocumentManifest_References
  DocumentManifest_Token
  DocumentReference
  DocumentReference_History
  DocumentReference_References
  DocumentReference_Token
  DomainConfiguration
  DomainConfiguration_History
  DomainConfiguration_References
  DomainConfiguration_Token
  EffectEvidenceSynthesis
  EffectEvidenceSynthesis_History
  EffectEvidenceSynthesis_References
  EffectEvidenceSynthesis_Token
  Encounter
  Encounter_History
  Encounter_References
  Encounter_Token
  Endpoint
  Endpoint_History
  Endpoint_References
  Endpoint_Token
  EnrollmentRequest
  EnrollmentRequest_History
  EnrollmentRequest_References
  EnrollmentRequest_Token
  EnrollmentResponse
  EnrollmentResponse_History
  EnrollmentResponse_References
  EnrollmentResponse_Token
  EpisodeOfCare
  EpisodeOfCare_History
  EpisodeOfCare_References
  EpisodeOfCare_Token
  EventDefinition
  EventDefinition_History
  EventDefinition_References
  EventDefinition_Token
  Evidence
  Evidence_History
  Evidence_References
  Evidence_Token
  EvidenceVariable
  EvidenceVariable_History
  EvidenceVariable_References
  EvidenceVariable_Token
  ExampleScenario
  ExampleScenario_History
  ExampleScenario_References
  ExampleScenario_Token
  ExplanationOfBenefit
  ExplanationOfBenefit_History
  ExplanationOfBenefit_References
  ExplanationOfBenefit_Token
  FamilyMemberHistory
  FamilyMemberHistory_History
  FamilyMemberHistory_References
  FamilyMemberHistory_Token
  Flag
  Flag_History
  Flag_References
  Flag_Token
  Goal
  Goal_History
  Goal_References
  Goal_Token
  GraphDefinition
  GraphDefinition_History
  GraphDefinition_References
  GraphDefinition_Token
  Group
  Group_History
  Group_References
  Group_Token
  GuidanceResponse
  GuidanceResponse_History
  GuidanceResponse_References
  GuidanceResponse_Token
  HealthcareService
  HealthcareService_History
  HealthcareService_References
  HealthcareService_Token
  HumanName
  Identifier
  ImagingStudy
  ImagingStudy_History
  ImagingStudy_References
  ImagingStudy_Token
  Immunization
  Immunization_History
  Immunization_References
  Immunization_Token
  ImmunizationEvaluation
  ImmunizationEvaluation_History
  ImmunizationEvaluation_References
  ImmunizationEvaluation_Token
  ImmunizationRecommendation
  ImmunizationRecommendation_History
  ImmunizationRecommendation_References
  ImmunizationRecommendation_Token
  ImplementationGuide
  ImplementationGuide_History
  ImplementationGuide_References
  ImplementationGuide_Token
  InsurancePlan
  InsurancePlan_History
  InsurancePlan_References
  InsurancePlan_Token
  Invoice
  Invoice_History
  Invoice_References
  Invoice_Token
  JsonWebKey
  JsonWebKey_History
  JsonWebKey_References
  JsonWebKey_Token
  Library
  Library_History
  Library_References
  Library_Token
  Linkage
  Linkage_History
  Linkage_References
  Linkage_Token
  List
  List_History
  List_References
  List_Token
  Location
  Location_History
  Location_References
  Location_Token
  Login
  Login_History
  Login_References
  Login_Token
  Measure
  Measure_History
  Measure_References
  Measure_Token
  MeasureReport
  MeasureReport_History
  MeasureReport_References
  MeasureReport_Token
  Media_History
  Media_References
  Media_Token
  Medication
  Medication_History
  Medication_References
  Medication_Token
  MedicationAdministration
  MedicationAdministration_History
  MedicationAdministration_References
  MedicationAdministration_Token
  MedicationDispense
  MedicationDispense_History
  MedicationDispense_References
  MedicationDispense_Token
  MedicationKnowledge
  MedicationKnowledge_History
  MedicationKnowledge_References
  MedicationKnowledge_Token
  MedicationRequest
  MedicationRequest_History
  MedicationRequest_References
  MedicationRequest_Token
  MedicationStatement
  MedicationStatement_History
  MedicationStatement_References
  MedicationStatement_Token
  MedicinalProduct
  MedicinalProduct_History
  MedicinalProduct_References
  MedicinalProduct_Token
  MedicinalProductAuthorization
  MedicinalProductAuthorization_History
  MedicinalProductAuthorization_References
  MedicinalProductAuthorization_Token
  MedicinalProductContraindication
  MedicinalProductContraindication_History
  MedicinalProductContraindication_References
  MedicinalProductContraindication_Token
  MedicinalProductIndication
  MedicinalProductIndication_History
  MedicinalProductIndication_References
  MedicinalProductIndication_Token
  MedicinalProductIngredient
  MedicinalProductIngredient_History
  MedicinalProductIngredient_References
  MedicinalProductIngredient_Token
  MedicinalProductInteraction
  MedicinalProductInteraction_History
  MedicinalProductInteraction_References
  MedicinalProductInteraction_Token
  MedicinalProductManufactured
  MedicinalProductManufactured_History
  MedicinalProductManufactured_References
  MedicinalProductManufactured_Token
  MedicinalProductPackaged
  MedicinalProductPackaged_History
  MedicinalProductPackaged_References
  MedicinalProductPackaged_Token
  MedicinalProductPharmaceutical
  MedicinalProductPharmaceutical_History
  MedicinalProductPharmaceutical_References
  MedicinalProductPharmaceutical_Token
  MedicinalProductUndesirableEffect
  MedicinalProductUndesirableEffect_History
  MedicinalProductUndesirableEffect_References
  MedicinalProductUndesirableEffect_Token
  MessageDefinition
  MessageDefinition_History
  MessageDefinition_References
  MessageDefinition_Token
  MessageHeader
  MessageHeader_History
  MessageHeader_References
  MessageHeader_Token
  MolecularSequence
  MolecularSequence_History
  MolecularSequence_References
  MolecularSequence_Token
  NamingSystem
  NamingSystem_History
  NamingSystem_References
  NamingSystem_Token
  NutritionOrder
  NutritionOrder_History
  NutritionOrder_References
  NutritionOrder_Token
  Observation
  Observation_History
  Observation_References
  Observation_Token
  ObservationDefinition
  ObservationDefinition_History
  ObservationDefinition_References
  ObservationDefinition_Token
  OperationDefinition
  OperationDefinition_History
  OperationDefinition_References
  OperationDefinition_Token
  OperationOutcome
  OperationOutcome_History
  OperationOutcome_References
  OperationOutcome_Token
  Organization
  Organization_History
  Organization_References
  Organization_Token
  OrganizationAffiliation
  OrganizationAffiliation_History
  OrganizationAffiliation_References
  OrganizationAffiliation_Token
  Parameters
  Parameters_History
  Parameters_References
  Parameters_Token
  PasswordChangeRequest
  PasswordChangeRequest_History
  PasswordChangeRequest_References
  PasswordChangeRequest_Token
  Patient
  Patient_History
  Patient_References
  Patient_Token
  PaymentNotice
  PaymentNotice_History
  PaymentNotice_References
  PaymentNotice_Token
  PaymentReconciliation
  PaymentReconciliation_History
  PaymentReconciliation_References
  PaymentReconciliation_Token
  Person
  Person_History
  Person_References
  Person_Token
  PlanDefinition
  PlanDefinition_History
  PlanDefinition_References
  PlanDefinition_Token
  Practitioner
  Practitioner_History
  Practitioner_References
  Practitioner_Token
  PractitionerRole
  PractitionerRole_History
  PractitionerRole_References
  PractitionerRole_Token
  Procedure
  Procedure_History
  Procedure_References
  Procedure_Token
  Project
  Project_History
  Project_References
  Project_Token
  ProjectMembership
  ProjectMembership_History
  ProjectMembership_References
  ProjectMembership_Token
  Provenance
  Provenance_History
  Provenance_References
  Provenance_Token
  Questionnaire
  Questionnaire_History
  Questionnaire_References
  Questionnaire_Token
  QuestionnaireResponse
  QuestionnaireResponse_History
  QuestionnaireResponse_References
  QuestionnaireResponse_Token
  RelatedPerson
  RelatedPerson_History
  RelatedPerson_References
  RelatedPerson_Token
  RequestGroup
  RequestGroup_History
  RequestGroup_References
  RequestGroup_Token
  ResearchDefinition
  ResearchDefinition_History
  ResearchDefinition_References
  ResearchDefinition_Token
  ResearchElementDefinition
  ResearchElementDefinition_History
  ResearchElementDefinition_References
  ResearchElementDefinition_Token
  ResearchStudy
  ResearchStudy_History
  ResearchStudy_References
  ResearchStudy_Token
  ResearchSubject
  ResearchSubject_History
  ResearchSubject_References
  ResearchSubject_Token
  RiskAssessment
  RiskAssessment_History
  RiskAssessment_References
  RiskAssessment_Token
  RiskEvidenceSynthesis
  RiskEvidenceSynthesis_History
  RiskEvidenceSynthesis_References
  RiskEvidenceSynthesis_Token
  Schedule
  Schedule_History
  Schedule_References
  Schedule_Token
  SearchParameter
  SearchParameter_History
  SearchParameter_References
  SearchParameter_Token
  ServiceRequest
  ServiceRequest_History
  ServiceRequest_References
  ServiceRequest_Token
  Slot
  Slot_History
  Slot_References
  Slot_Token
  SmartAppLaunch
  SmartAppLaunch_History
  SmartAppLaunch_References
  SmartAppLaunch_Token
  Specimen
  Specimen_History
  Specimen_References
  Specimen_Token
  SpecimenDefinition
  SpecimenDefinition_History
  SpecimenDefinition_References
  SpecimenDefinition_Token
  StructureDefinition
  StructureDefinition_History
  StructureDefinition_References
  StructureDefinition_Token
  StructureMap
  StructureMap_History
  StructureMap_References
  StructureMap_Token
  Subscription
  Subscription_History
  Subscription_References
  Subscription_Token
  SubscriptionStatus
  SubscriptionStatus_History
  SubscriptionStatus_References
  SubscriptionStatus_Token
  Substance
  Substance_History
  Substance_References
  Substance_Token
  SubstanceNucleicAcid
  SubstanceNucleicAcid_History
  SubstanceNucleicAcid_References
  SubstanceNucleicAcid_Token
  SubstancePolymer
  SubstancePolymer_History
  SubstancePolymer_References
  SubstancePolymer_Token
  SubstanceProtein
  SubstanceProtein_History
  SubstanceProtein_References
  SubstanceProtein_Token
  SubstanceReferenceInformation
  SubstanceReferenceInformation_History
  SubstanceReferenceInformation_References
  SubstanceReferenceInformation_Token
  SubstanceSourceMaterial
  SubstanceSourceMaterial_History
  SubstanceSourceMaterial_References
  SubstanceSourceMaterial_Token
  SubstanceSpecification
  SubstanceSpecification_History
  SubstanceSpecification_References
  SubstanceSpecification_Token
  SupplyDelivery
  SupplyDelivery_History
  SupplyDelivery_References
  SupplyDelivery_Token
  SupplyRequest
  SupplyRequest_History
  SupplyRequest_References
  SupplyRequest_Token
  Task
  Task_History
  Task_References
  Task_Token
  TerminologyCapabilities
  TerminologyCapabilities_History
  TerminologyCapabilities_References
  TerminologyCapabilities_Token
  TestReport
  TestReport_History
  TestReport_References
  TestReport_Token
  TestScript
  TestScript_History
  TestScript_References
  TestScript_Token
  User
  User_History
  User_References
  User_Token
  UserConfiguration
  UserConfiguration_History
  UserConfiguration_References
  UserConfiguration_Token
  UserSecurityRequest
  UserSecurityRequest_History
  UserSecurityRequest_References
  UserSecurityRequest_Token
  ValueSet
  ValueSet_History
  ValueSet_Membership
  ValueSet_References
  ValueSet_Token
  ValueSetElement
  VerificationResult
  VerificationResult_History
  VerificationResult_References
  VerificationResult_Token
  VisionPrescription
  VisionPrescription_History
  VisionPrescription_References
  VisionPrescription_Token
)

exclude_patterns=''
for table in "${MEDPLUM_TABLES[@]}"; do
  found=false
  for item in "${MEDPLUM_TABLES_IN_USE[@]}"; do
    if [[ "$item" == "$table" ]]; then
      found=true
      break
    fi
  done

  echo "$table $found"

  if ! $found; then
    exclude_patterns="$exclude_patterns --exclude-pattern $table"
  fi
done

echo $exclude_patterns

cd ./db/codegen
npm install
cd ../..
# shellcheck disable=SC2086
./db/codegen/node_modules/.bin/kysely-codegen $exclude_patterns --out-file db.d.ts

echo 'type Buffer = Uint8Array' >> db.d.ts

deno fmt db.d.ts