export default [
  {
    'medicine_row': {
      'PUBLICATION': 'Paediatric Hospital Level',
      'LEVEL OF CARE': 'Hospital',
      'CHAPTER NUMBER': '4',
      'CHAPTER NAME': 'Cardiovascular System',
      'SECTION NUMBER': '4.11',
      'STG/DISORDER GROUP': 'Hypertension in Children',
      'DISORDER NUMBER': '4.11.2',
      'DISORDER': 'Hypertension, chronic',
      'ICD10 CODE': 'I10',
      'MEDICINE NAME (International Nonproprietary Name)': 'Enalapril',
      'DOSAGE FORM': 'Tablet/capsule/granules',
      'DOSE': '0.04 mg/kg/dose (maximum = 0.3 mg/kg/dose up to 40 mg)',
      'DOSING INTERVAL': '12 hourly',
      'DURATION OF TREATMENT': null,
      'ROUTE OF ADMINISTRATION': 'Oral',
      'DDD': 'Paed',
      'ATC': 'C09AA02',
      'AWaRe categorisation of antibiotics': 'n/a',
      'VEN': null,
      'ACUTE/CHRONIC': 'Chronic',
      'ADULT/ CHILDREN': 'Children',
      'PRESCRIBER': 'Doctor prescribed',
    },
    'error_message': '',
    'error_stack':
      'AssertionError\n    at assert (https://deno.land/std@0.224.0/assert/assert.ts:18:11)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:123:13)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:39\n    at Array.forEach (<anonymous>)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:18)\n    at new MedicineParser (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:81:10)\n    at MedicineParser.parse (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:17:12)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:50\n    at asResult (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/util/asResult.ts:5:19)\n    at parseAll (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:20)',
  },
  {
    'medicine_row': {
      'PUBLICATION': 'Paediatric Hospital Level',
      'LEVEL OF CARE': 'Hospital',
      'CHAPTER NUMBER': '7',
      'CHAPTER NAME': 'Endocrine system',
      'SECTION NUMBER': '7.5',
      'STG/DISORDER GROUP': 'Diabetes Mellitus',
      'DISORDER NUMBER': '7.5.2.4',
      'DISORDER': 'Insulin Dependent: Acute Complications - Diabetic Nephropathy',
      'ICD10 CODE': 'E10.21',
      'MEDICINE NAME (International Nonproprietary Name)': 'Enalapril',
      'DOSAGE FORM': 'Tablet/capsule/granules',
      'DOSE': '0.1mg/kg/dose (maximum dose = 0.5mg/kg or 40mg/day)',
      'DOSING INTERVAL': 'once or twice daily',
      'DURATION OF TREATMENT': null,
      'ROUTE OF ADMINISTRATION': 'Oral',
      'DDD': 'Paed',
      'ATC': 'C09AA02',
      'AWaRe categorisation of antibiotics': 'n/a',
      'VEN': null,
      'ACUTE/CHRONIC': 'Acute',
      'ADULT/ CHILDREN': 'Children',
      'PRESCRIBER': 'Doctor prescribed',
    },
    'error_message': '',
    'error_stack':
      'AssertionError\n    at assert (https://deno.land/std@0.224.0/assert/assert.ts:18:11)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:123:13)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:39\n    at Array.forEach (<anonymous>)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:18)\n    at new MedicineParser (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:81:10)\n    at MedicineParser.parse (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:17:12)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:50\n    at asResult (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/util/asResult.ts:5:19)\n    at parseAll (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:20)',
  },
  {
    'medicine_row': {
      'PUBLICATION': 'Paediatric Hospital Level',
      'LEVEL OF CARE': 'Hospital',
      'CHAPTER NUMBER': '13',
      'CHAPTER NAME': 'The Nervous System',
      'SECTION NUMBER': '13.2',
      'STG/DISORDER GROUP': 'Status Epilepticus',
      'DISORDER NUMBER': '13.2.1',
      'DISORDER':
        'Status Epilepticus - Epileptic seizures and status epilepticus in children < 13 years of age - Established status - phenobarbital given and no response 5 mins after administration',
      'ICD10 CODE': 'G41.9',
      'MEDICINE NAME (International Nonproprietary Name)': 'Phenytoin',
      'DOSAGE FORM': 'Injection',
      'DOSE': '20mg/kg (maximum 600mg/dose)',
      'DOSING INTERVAL': 'over 20 minutes (maximum = 3mg/kg/min)',
      'DURATION OF TREATMENT': null,
      'ROUTE OF ADMINISTRATION': 'Intravenous injection (IV)',
      'DDD': 'Paed',
      'ATC': 'N03AB02',
      'AWaRe categorisation of antibiotics': 'n/a',
      'VEN': null,
      'ACUTE/CHRONIC': 'Acute',
      'ADULT/ CHILDREN': 'Children',
      'PRESCRIBER': 'Doctor prescribed',
    },
    'error_message': '',
    'error_stack':
      'AssertionError\n    at assert (https://deno.land/std@0.224.0/assert/assert.ts:18:11)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:123:13)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:39\n    at Array.forEach (<anonymous>)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:18)\n    at new MedicineParser (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:81:10)\n    at MedicineParser.parse (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:17:12)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:50\n    at asResult (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/util/asResult.ts:5:19)\n    at parseAll (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:20)',
  },
  {
    'medicine_row': {
      'PUBLICATION': 'Paediatric Hospital Level',
      'LEVEL OF CARE': 'Hospital',
      'CHAPTER NUMBER': '14',
      'CHAPTER NAME': 'Child and Adolescent Psychiatry',
      'SECTION NUMBER': '14.3',
      'STG/DISORDER GROUP': 'Attention Deficit Hyperactivity Disorder (ADHD)',
      'DISORDER NUMBER': '14.3',
      'DISORDER': 'Attention Defecit Hyperactivity Disorder (ADHD) - >6 years of age',
      'ICD10 CODE': 'F90.0-F90.9',
      'MEDICINE NAME (International Nonproprietary Name)': 'Methylphenidate - short acting only',
      'DOSAGE FORM': 'Tablet/capsule/granules',
      'DOSE': '1mg/kg/day (maximum daily dose = 60mg = 2mg/kg/day)',
      'DOSING INTERVAL': '2 - 3 times daily (every 3 - 3.5 hours (at breakfast, lunch and no later than 14h30))',
      'DURATION OF TREATMENT': null,
      'ROUTE OF ADMINISTRATION': 'Oral',
      'DDD': 'Paed',
      'ATC': 'N06BA04',
      'AWaRe categorisation of antibiotics': 'n/a',
      'VEN': null,
      'ACUTE/CHRONIC': 'Acute',
      'ADULT/ CHILDREN': 'Children',
      'PRESCRIBER': 'Doctor prescribed',
    },
    'error_message': '',
    'error_stack':
      'AssertionError\n    at assert (https://deno.land/std@0.224.0/assert/assert.ts:18:11)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:123:13)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:39\n    at Array.forEach (<anonymous>)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:18)\n    at new MedicineParser (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:81:10)\n    at MedicineParser.parse (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:17:12)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:50\n    at asResult (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/util/asResult.ts:5:19)\n    at parseAll (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:20)',
  },
  {
    'medicine_row': {
      'PUBLICATION': 'Paediatric Hospital Level',
      'LEVEL OF CARE': 'Hospital',
      'CHAPTER NUMBER': '21',
      'CHAPTER NAME': 'Palliative Care',
      'SECTION NUMBER': '21.1',
      'STG/DISORDER GROUP': 'Symptom Control',
      'DISORDER NUMBER': '21.1.1.2',
      'DISORDER': 'Gastro-intestinal symptoms - Nausea and vomiting - 1–11 months (up to 10 kg)',
      'ICD10 CODE': 'R11',
      'MEDICINE NAME (International Nonproprietary Name)': 'Metoclopramide',
      'DOSAGE FORM': 'Solution',
      'DOSE': '100 mcg/kg (maximum = 1000 mcg/dose = 1mg/dose)',
      'DOSING INTERVAL': '12 hourly',
      'DURATION OF TREATMENT': null,
      'ROUTE OF ADMINISTRATION': 'Oral',
      'DDD': 'Paed',
      'ATC': 'A03FA01',
      'AWaRe categorisation of antibiotics': 'n/a',
      'VEN': null,
      'ACUTE/CHRONIC': 'Acute',
      'ADULT/ CHILDREN': 'Children',
      'PRESCRIBER': 'Doctor prescribed',
    },
    'error_message': '',
    'error_stack':
      'AssertionError\n    at assert (https://deno.land/std@0.224.0/assert/assert.ts:18:11)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:123:13)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:39\n    at Array.forEach (<anonymous>)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:18)\n    at new MedicineParser (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:81:10)\n    at MedicineParser.parse (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:17:12)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:50\n    at asResult (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/util/asResult.ts:5:19)\n    at parseAll (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:20)',
  },
  {
    'medicine_row': {
      'PUBLICATION': 'Paediatric Hospital Level',
      'LEVEL OF CARE': 'Hospital',
      'CHAPTER NUMBER': '21',
      'CHAPTER NAME': 'Palliative Care',
      'SECTION NUMBER': '21.1',
      'STG/DISORDER GROUP': 'Symptom Control',
      'DISORDER NUMBER': '21.1.1.2',
      'DISORDER': 'Gastro-intestinal symptoms - Nausea and vomiting - 1–11 months (up to 10 kg)',
      'ICD10 CODE': 'R11',
      'MEDICINE NAME (International Nonproprietary Name)': 'Metoclopramide',
      'DOSAGE FORM': 'Injection',
      'DOSE': '100 mcg/kg (maximum = 1000 mcg/dose = 1mg/dose)',
      'DOSING INTERVAL': '12 hourly',
      'DURATION OF TREATMENT': null,
      'ROUTE OF ADMINISTRATION': 'Intravenous injection (IV)',
      'DDD': 'Paed',
      'ATC': 'A03FA01',
      'AWaRe categorisation of antibiotics': 'n/a',
      'VEN': null,
      'ACUTE/CHRONIC': 'Acute',
      'ADULT/ CHILDREN': 'Children',
      'PRESCRIBER': 'Doctor prescribed',
    },
    'error_message': '',
    'error_stack':
      'AssertionError\n    at assert (https://deno.land/std@0.224.0/assert/assert.ts:18:11)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:123:13)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:39\n    at Array.forEach (<anonymous>)\n    at MedicineParser.extractMax (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:117:18)\n    at new MedicineParser (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:81:10)\n    at MedicineParser.parse (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/MedicineParser.ts:17:12)\n    at file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:50\n    at asResult (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/util/asResult.ts:5:19)\n    at parseAll (file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/backend/recommended_doses/parser.ts:12:20)',
  },
]
