;; Page 37 - Chest Pain
(task
  "Check for urgent chest pain conditions"
  adult
  (clinical_finding (snomed_concept "Chest pain" "finding"))
  (check_for
    (>= (measurement (snomed_concept "Respiratory rate" "observable entity") bpm) 30)
    (and
      (>= (measurement (snomed_concept "Systolic blood pressure" "observable entity") mmhg) 180)
      (>= (measurement (snomed_concept "Diastolic blood pressure" "observable entity") mmhg) 110))
    (or
      (<= (measurement (snomed_concept "Systolic blood pressure" "observable entity") mmhg) 90)
      (<= (measurement (snomed_concept "Diastolic blood pressure" "observable entity") mmhg) 60))
    (clinical_finding (snomed_concept "Pulse irregular" "finding"))
    (> (measurement (snomed_concept "Heart rate measured at systemic artery" "observable entity") bpm) 100)
    (< (measurement (snomed_concept "Heart rate measured at systemic artery" "observable entity") bpm) 50)
    (clinical_finding (snomed_concept "Severe pain" "finding"))
    (clinical_finding (snomed_concept "Chest pain" "finding") (qualifier (snomed_concept "New" "qualifier value")))
    (clinical_finding (snomed_concept "Chest discomfort" "finding") (qualifier (snomed_concept "New" "qualifier value")))
    (clinical_finding (snomed_concept "Nausea" "finding"))
    (clinical_finding (snomed_concept "Vomiting" "disorder"))
    (clinical_finding (snomed_concept "Pallor of skin of face" "finding"))
    (clinical_finding (snomed_concept "Sweating" "finding"))
    (clinical_finding (snomed_concept "Radiating chest pain" "finding"))
    (clinical_finding (snomed_concept "Pain radiating to jaw" "finding"))
    (clinical_finding (snomed_concept "Pain radiating to neck" "finding"))
    (clinical_finding (snomed_concept "Pain radiating to left arm" "finding"))
    (clinical_finding (snomed_concept "Pain radiating to right arm" "finding"))
    (clinical_finding (snomed_concept "Pain radiating to left shoulder" "finding"))
    (clinical_finding (snomed_concept "Pain radiating to right shoulder" "finding"))
    (clinical_finding (snomed_concept "Difficulty breathing" "finding"))
    (clinical_finding (snomed_concept "History of treatment for ischemic heart disease" "situation"))
    (clinical_finding (snomed_concept "Diabetes mellitus" "disorder") (qualifier (snomed_concept "Known present" "qualifier value")))
    (clinical_finding (snomed_concept "Smoker" "finding"))
    (clinical_finding (snomed_concept "Hypertensive disorder, systemic arterial" "disorder") (qualifier (snomed_concept "Known present" "qualifier value")))
    (clinical_finding (snomed_concept "Hypercholesterolemia" "disorder") (qualifier (snomed_concept "Known present" "qualifier value")))
    (>= (measurement (snomed_concept "Risk of cardiovascular disease" "observable entity") %) 20)
    (clinical_finding (snomed_concept "Family history of ischemic heart disease" "situation"))
    (clinical_finding (snomed_concept "ST segment elevation" "finding"))
    (clinical_finding (snomed_concept "ST segment depression" "finding"))
    (clinical_finding (snomed_concept "Electrocardiographic left bundle branch block" "finding"))
    (clinical_finding (snomed_concept "Chest pain on breathing" "finding"))
    (clinical_finding (snomed_concept "Pleuritic pain" "finding"))
  )
)
