export const BODY_PARTS: Array<[string, string[]]> = [
  ['Head', [
    'Forehead',
    'Left Side Head',
    'Right Side Head',
    'Back Side Head',
    'Front Side Head',
    'Generalized Head',
  ]],
  ['Face', [
    'Left Side Face',
    'Right Side Face',
    'Generalized Face',
  ]],
  ['Mouth', [
    'Upper Lip',
    'Lower Lip',
    'Gums',
    'Tongue',
  ]],
  ['Eye', [
    'Left Eye',
    'Right Eye',
    'Both Eyes',
  ]],
  ['Ear', [
    'Left Ear',
    'Right Ear',
    'Both Ears',
  ]],
  ['Nose', [
    'Left Side Nose',
    'Right Side Nose',
    'Generalized Nose',
  ]],
  ['Neck', [
    'Throat',
    'Left Side Neck',
    'Right Side Neck',
    'Back Side Neck',
    'Front Side Neck',
    'Generalized Neck',
  ]],
  ['Chest', [
    'Left Side Chest',
    'Right Side Chest',
    'Central Chest',
    'Generalized Chest',
  ]],
  ['Breast', [
    'Left Breast',
    'Right Breast',
    'Both Breasts',
  ]],
  ['Abdomen', [
    'Left Abdomen',
    'Right Abdomen',
    'General Abdomen',
  ]],
  ['Arm', [
    'Left Arm',
    'Right Arm',
    'Both Arms',
  ]],
  ['Elbow', [
    'Left Elbow',
    'Right Elbow',
    'Both Elbows',
  ]],
  ['Forearm', [
    'Left Forearm',
    'Right Forearm',
    'Both Forearms',
  ]],
  ['Hip', [
    'Left Hip',
    'Right Hip',
    'Both Hips',
  ]],
  ['Wrist', [
    'Left Wrist',
    'Right Wrist',
    'Both Wrists',
  ]],
  ['Hand', [
    'Left Hand',
    'Right Hand',
    'Both Hands',
  ]],
  ['Fingers', [
    'Left Index Finger',
    'Left Middle Finger',
    'Left Ring Finger',
    'Left Little Finger',
    'Left Thumb',
    'Right Index Finger',
    'Right Middle Finger',
    'Right Ring Finger',
    'Right Little Finger',
    'Right Thumb',
  ]],
  ['Groin', [
    'Pelvis',
    'Penis',
    'Urethra',
    'Vagina ',
    'Clitoris',
    'Vulva',
    'Anus',
    'Scrotum',
  ]],
  ['Thigh', [
    'Left Thigh',
    'Right Thigh',
    'Both Thighs',
  ]],
  ['Knee', [
    'Left Knee',
    'Right Knee',
    'Both Knees',
  ]],
  ['Leg', [
    'Left Leg',
    'Right Leg',
    'Both Legs',
  ]],
  ['Ankle', [
    'Left Ankle',
    'Right Ankle',
    'Both Ankles',
  ]],
  ['Toes', [
    'Left Big Toe',
    'Left Index Toe',
    'Left Middle Toe',
    'Left Ring Toe',
    'Left Little Toe',
    'Right Big Toe',
    'Right Index Toe',
    'Right Middle Toe',
    'Right Ring Toe',
    'Right Little Toe',
  ]],
  ['Foot', [
    'Right Foot',
    'Left Foot',
    'Both Feet',
  ]],
  ['Shoulder', [
    'Left Shoulder',
    'Right Shoulder',
    'Both Shoulders',
  ]],
  ['Back', [
    'Upper Back',
    'Lower Back',
    'Central Back',
    'Generalized Back',
  ]],
  ['Upper Limb', [
    'Left Upper Limb',
    'Right Upper Limb',
  ]],
  ['Lower Limb', [
    'Left Lower Limb',
    'Right Lower Limb',
  ]],
  ['Buttock', [
    'Left Buttock',
    'Right Buttock',
    'Both Buttocks',
  ]],
  ['Calf', [
    'Left Calf',
    'Right Calf',
    'Both Calves',
  ]],
  ['Heel', [
    'Left Heel',
    'Right Heel',
    'Both Heels',
  ]],
  ['Sole', [
    'Left Foot Sole',
    'Right Foot Sole',
    'Both Soles',
  ]],
]
