import { CommonSymptom } from '../types.ts'
import { normalForm } from './s_expression.ts'

export const COMMON_SYMPTOMS: CommonSymptom[] = [
  {
    'key': 'Nasal discharge' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Nasal discharge" "finding"))`),
    'primary_name': 'Nasal discharge',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Fever' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Fever" "finding"))`),
    'primary_name': 'Fever',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Cough' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Cough" "finding"))`),
    'primary_name': 'Cough',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Sore throat' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Sore throat" "finding"))`),
    'primary_name': 'Sore throat',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Headache' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Headache" "finding"))`),
    'primary_name': 'Headache',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Fatigue' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Fatigue" "finding"))`),
    'primary_name': 'Fatigue',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Dyspnea' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Dyspnea" "finding"))`),
    'primary_name': 'Shortness of breath',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Nausea' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Nausea" "finding"))`),
    'primary_name': 'Nausea',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Vomiting' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Finding of vomiting" "finding"))`),
    'primary_name': 'Vomiting',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Diarrhea' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Diarrhea" "finding"))`),
    'primary_name': 'Diarrhea',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Dizziness' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Dizziness" "finding"))`),
    'primary_name': 'Dizziness',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Muscle pain' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Muscle pain" "finding"))`),
    'primary_name': 'Muscle pain',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Pain of joint' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Pain of joint" "finding"))`),
    'primary_name': 'Pain of joint',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Backache' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Backache" "finding"))`),
    'primary_name': 'Back pain',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
  {
    'key': 'Constipation' as const,
    'clinical_finding_s_expression': normalForm(`(clinical_finding (snomed_concept "Constipation" "finding"))`),
    'primary_name': 'Constipation',
    'secondary_text': null,
    'category': 'Common Symptoms' as const,
  },
]
