export const COUNTRIES = [
  {
    'iso_3166_2': 'AF',
    'iso_3166_3': 'AFG',
    'official_name': 'Afghanistan',
    'alternate_names': null,
    'emoji': '🇦🇫',
    'phone_calling_code': '93',
  },
  {
    'iso_3166_2': 'AX',
    'iso_3166_3': 'ALA',
    'official_name': 'Åland Islands',
    'alternate_names': null,
    'emoji': '🇦🇽',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'AL',
    'iso_3166_3': 'ALB',
    'official_name': 'Albania',
    'alternate_names': null,
    'emoji': '🇦🇱',
    'phone_calling_code': '355',
  },
  {
    'iso_3166_2': 'DZ',
    'iso_3166_3': 'DZA',
    'official_name': 'Algeria',
    'alternate_names': null,
    'emoji': '🇩🇿',
    'phone_calling_code': '213',
  },
  {
    'iso_3166_2': 'AS',
    'iso_3166_3': 'ASM',
    'official_name': 'American Samoa',
    'alternate_names': null,
    'emoji': '🇦🇸',
    'phone_calling_code': '1-684',
  },
  {
    'iso_3166_2': 'AD',
    'iso_3166_3': 'AND',
    'official_name': 'Andorra',
    'alternate_names': null,
    'emoji': '🇦🇩',
    'phone_calling_code': '376',
  },
  {
    'iso_3166_2': 'AO',
    'iso_3166_3': 'AGO',
    'official_name': 'Angola',
    'alternate_names': null,
    'emoji': '🇦🇴',
    'phone_calling_code': '244',
  },
  {
    'iso_3166_2': 'AI',
    'iso_3166_3': 'AIA',
    'official_name': 'Anguilla',
    'alternate_names': null,
    'emoji': '🇦🇮',
    'phone_calling_code': '1-264',
  },
  {
    'iso_3166_2': 'AQ',
    'iso_3166_3': 'ATA',
    'official_name': 'Antarctica',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': '672',
  },
  {
    'iso_3166_2': 'AG',
    'iso_3166_3': 'ATG',
    'official_name': 'Antigua and Barbuda',
    'alternate_names': null,
    'emoji': '🇦🇬',
    'phone_calling_code': '1-268',
  },
  {
    'iso_3166_2': 'AR',
    'iso_3166_3': 'ARG',
    'official_name': 'Argentina',
    'alternate_names': null,
    'emoji': '🇦🇷',
    'phone_calling_code': '54',
  },
  {
    'iso_3166_2': 'AM',
    'iso_3166_3': 'ARM',
    'official_name': 'Armenia',
    'alternate_names': null,
    'emoji': '🇦🇲',
    'phone_calling_code': '374',
  },
  {
    'iso_3166_2': 'AW',
    'iso_3166_3': 'ABW',
    'official_name': 'Aruba',
    'alternate_names': null,
    'emoji': '🇦🇼',
    'phone_calling_code': '297',
  },
  {
    'iso_3166_2': 'AU',
    'iso_3166_3': 'AUS',
    'official_name': 'Australia',
    'alternate_names': null,
    'emoji': '🇦🇺',
    'phone_calling_code': '61',
  },
  {
    'iso_3166_2': 'AT',
    'iso_3166_3': 'AUT',
    'official_name': 'Austria',
    'alternate_names': null,
    'emoji': '🇦🇹',
    'phone_calling_code': '43',
  },
  {
    'iso_3166_2': 'AZ',
    'iso_3166_3': 'AZE',
    'official_name': 'Azerbaijan',
    'alternate_names': null,
    'emoji': '🇦🇿',
    'phone_calling_code': '994',
  },
  {
    'iso_3166_2': 'BS',
    'iso_3166_3': 'BHS',
    'official_name': 'Bahamas',
    'alternate_names': null,
    'emoji': '🇧🇸',
    'phone_calling_code': '1-242',
  },
  {
    'iso_3166_2': 'BH',
    'iso_3166_3': 'BHR',
    'official_name': 'Bahrain',
    'alternate_names': null,
    'emoji': '🇧🇭',
    'phone_calling_code': '973',
  },
  {
    'iso_3166_2': 'BD',
    'iso_3166_3': 'BGD',
    'official_name': 'Bangladesh',
    'alternate_names': null,
    'emoji': '🇧🇩',
    'phone_calling_code': '880',
  },
  {
    'iso_3166_2': 'BB',
    'iso_3166_3': 'BRB',
    'official_name': 'Barbados',
    'alternate_names': null,
    'emoji': '🇧🇧',
    'phone_calling_code': '1-246',
  },
  {
    'iso_3166_2': 'BY',
    'iso_3166_3': 'BLR',
    'official_name': 'Belarus',
    'alternate_names': null,
    'emoji': '🇧🇾',
    'phone_calling_code': '375',
  },
  {
    'iso_3166_2': 'BE',
    'iso_3166_3': 'BEL',
    'official_name': 'Belgium',
    'alternate_names': null,
    'emoji': '🇧🇪',
    'phone_calling_code': '32',
  },
  {
    'iso_3166_2': 'BZ',
    'iso_3166_3': 'BLZ',
    'official_name': 'Belize',
    'alternate_names': null,
    'emoji': '🇧🇿',
    'phone_calling_code': '501',
  },
  {
    'iso_3166_2': 'BJ',
    'iso_3166_3': 'BEN',
    'official_name': 'Benin',
    'alternate_names': null,
    'emoji': '🇧🇯',
    'phone_calling_code': '229',
  },
  {
    'iso_3166_2': 'BM',
    'iso_3166_3': 'BMU',
    'official_name': 'Bermuda',
    'alternate_names': null,
    'emoji': '🇧🇲',
    'phone_calling_code': '1-441',
  },
  {
    'iso_3166_2': 'BT',
    'iso_3166_3': 'BTN',
    'official_name': 'Bhutan',
    'alternate_names': null,
    'emoji': '🇧🇹',
    'phone_calling_code': '975',
  },
  {
    'iso_3166_2': 'BO',
    'iso_3166_3': 'BOL',
    'official_name': 'Bolivia, Plurinational State of',
    'alternate_names': 'Bolivia',
    'emoji': '🇧🇴',
    'phone_calling_code': '591',
  },
  {
    'iso_3166_2': 'BQ',
    'iso_3166_3': 'BES',
    'official_name': 'Bonaire, Sint Eustatius and Saba',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'BA',
    'iso_3166_3': 'BIH',
    'official_name': 'Bosnia and Herzegovina',
    'alternate_names': null,
    'emoji': '🇧🇦',
    'phone_calling_code': '387',
  },
  {
    'iso_3166_2': 'BW',
    'iso_3166_3': 'BWA',
    'official_name': 'Botswana',
    'alternate_names': null,
    'emoji': '🇧🇼',
    'phone_calling_code': '267',
  },
  {
    'iso_3166_2': 'BV',
    'iso_3166_3': 'BVT',
    'official_name': 'Bouvet Island',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'BR',
    'iso_3166_3': 'BRA',
    'official_name': 'Brazil',
    'alternate_names': null,
    'emoji': '🇧🇷',
    'phone_calling_code': '55',
  },
  {
    'iso_3166_2': 'IO',
    'iso_3166_3': 'IOT',
    'official_name': 'British Indian Ocean Territory',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': '246',
  },
  {
    'iso_3166_2': 'BN',
    'iso_3166_3': 'BRN',
    'official_name': 'Brunei Darussalam',
    'alternate_names': null,
    'emoji': '🇧🇳',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'BG',
    'iso_3166_3': 'BGR',
    'official_name': 'Bulgaria',
    'alternate_names': null,
    'emoji': '🇧🇬',
    'phone_calling_code': '359',
  },
  {
    'iso_3166_2': 'BF',
    'iso_3166_3': 'BFA',
    'official_name': 'Burkina Faso',
    'alternate_names': null,
    'emoji': '🇧🇫',
    'phone_calling_code': '226',
  },
  {
    'iso_3166_2': 'BI',
    'iso_3166_3': 'BDI',
    'official_name': 'Burundi',
    'alternate_names': null,
    'emoji': '🇧🇮',
    'phone_calling_code': '257',
  },
  {
    'iso_3166_2': 'KH',
    'iso_3166_3': 'KHM',
    'official_name': 'Cambodia',
    'alternate_names': null,
    'emoji': '🇰🇭',
    'phone_calling_code': '855',
  },
  {
    'iso_3166_2': 'CM',
    'iso_3166_3': 'CMR',
    'official_name': 'Cameroon',
    'alternate_names': null,
    'emoji': '🇨🇲',
    'phone_calling_code': '237',
  },
  {
    'iso_3166_2': 'CA',
    'iso_3166_3': 'CAN',
    'official_name': 'Canada',
    'alternate_names': null,
    'emoji': '🇨🇦',
    'phone_calling_code': '1',
  },
  {
    'iso_3166_2': 'CV',
    'iso_3166_3': 'CPV',
    'official_name': 'Cabo Verde',
    'alternate_names': 'Cape Verde',
    'emoji': '🇨🇻',
    'phone_calling_code': '238',
  },
  {
    'iso_3166_2': 'KY',
    'iso_3166_3': 'CYM',
    'official_name': 'Cayman Islands',
    'alternate_names': null,
    'emoji': '🇰🇾',
    'phone_calling_code': '1-345',
  },
  {
    'iso_3166_2': 'CF',
    'iso_3166_3': 'CAF',
    'official_name': 'Central African Republic',
    'alternate_names': null,
    'emoji': '🇨🇫',
    'phone_calling_code': '236',
  },
  {
    'iso_3166_2': 'TD',
    'iso_3166_3': 'TCD',
    'official_name': 'Chad',
    'alternate_names': null,
    'emoji': '🇹🇩',
    'phone_calling_code': '235',
  },
  {
    'iso_3166_2': 'CL',
    'iso_3166_3': 'CHL',
    'official_name': 'Chile',
    'alternate_names': null,
    'emoji': '🇨🇱',
    'phone_calling_code': '56',
  },
  {
    'iso_3166_2': 'CN',
    'iso_3166_3': 'CHN',
    'official_name': 'China',
    'alternate_names': null,
    'emoji': '🇨🇳',
    'phone_calling_code': '86',
  },
  {
    'iso_3166_2': 'CX',
    'iso_3166_3': 'CXR',
    'official_name': 'Christmas Island',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': '61',
  },
  {
    'iso_3166_2': 'CC',
    'iso_3166_3': 'CCK',
    'official_name': 'Cocos (Keeling) Islands',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'CO',
    'iso_3166_3': 'COL',
    'official_name': 'Colombia',
    'alternate_names': null,
    'emoji': '🇨🇴',
    'phone_calling_code': '57',
  },
  {
    'iso_3166_2': 'KM',
    'iso_3166_3': 'COM',
    'official_name': 'Comoros',
    'alternate_names': null,
    'emoji': '🇰🇲',
    'phone_calling_code': '269',
  },
  {
    'iso_3166_2': 'CD',
    'iso_3166_3': 'COD',
    'official_name': 'Congo, Democratic Republic of the',
    'alternate_names': 'Congo, the Democratic Republic of the',
    'emoji': '🇨🇩',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'CG',
    'iso_3166_3': 'COG',
    'official_name': 'Congo',
    'alternate_names': null,
    'emoji': '🇨🇬',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'CK',
    'iso_3166_3': 'COK',
    'official_name': 'Cook Islands',
    'alternate_names': null,
    'emoji': '🇨🇰',
    'phone_calling_code': '682',
  },
  {
    'iso_3166_2': 'CR',
    'iso_3166_3': 'CRI',
    'official_name': 'Costa Rica',
    'alternate_names': null,
    'emoji': '🇨🇷',
    'phone_calling_code': '506',
  },
  {
    'iso_3166_2': 'CI',
    'iso_3166_3': 'CIV',
    'official_name': "Côte d'Ivoire",
    'alternate_names': null,
    'emoji': '🇨🇮',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'HR',
    'iso_3166_3': 'HRV',
    'official_name': 'Croatia',
    'alternate_names': null,
    'emoji': '🇭🇷',
    'phone_calling_code': '385',
  },
  {
    'iso_3166_2': 'CU',
    'iso_3166_3': 'CUB',
    'official_name': 'Cuba',
    'alternate_names': null,
    'emoji': '🇨🇺',
    'phone_calling_code': '53',
  },
  {
    'iso_3166_2': 'CW',
    'iso_3166_3': 'CUW',
    'official_name': 'Curaçao',
    'alternate_names': null,
    'emoji': '🇨🇼',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'CY',
    'iso_3166_3': 'CYP',
    'official_name': 'Cyprus',
    'alternate_names': null,
    'emoji': '🇨🇾',
    'phone_calling_code': '357',
  },
  {
    'iso_3166_2': 'CZ',
    'iso_3166_3': 'CZE',
    'official_name': 'Czechia',
    'alternate_names': 'Czech Republic',
    'emoji': '🇨🇿',
    'phone_calling_code': '420',
  },
  {
    'iso_3166_2': 'DK',
    'iso_3166_3': 'DNK',
    'official_name': 'Denmark',
    'alternate_names': null,
    'emoji': '🇩🇰',
    'phone_calling_code': '45',
  },
  {
    'iso_3166_2': 'DJ',
    'iso_3166_3': 'DJI',
    'official_name': 'Djibouti',
    'alternate_names': null,
    'emoji': '🇩🇯',
    'phone_calling_code': '253',
  },
  {
    'iso_3166_2': 'DM',
    'iso_3166_3': 'DMA',
    'official_name': 'Dominica',
    'alternate_names': null,
    'emoji': '🇩🇲',
    'phone_calling_code': '1-767',
  },
  {
    'iso_3166_2': 'DO',
    'iso_3166_3': 'DOM',
    'official_name': 'Dominican Republic',
    'alternate_names': null,
    'emoji': '🇩🇴',
    'phone_calling_code': '1-809, 1-829, 1-849',
  },
  {
    'iso_3166_2': 'EC',
    'iso_3166_3': 'ECU',
    'official_name': 'Ecuador',
    'alternate_names': null,
    'emoji': '🇪🇨',
    'phone_calling_code': '593',
  },
  {
    'iso_3166_2': 'EG',
    'iso_3166_3': 'EGY',
    'official_name': 'Egypt',
    'alternate_names': null,
    'emoji': '🇪🇬',
    'phone_calling_code': '20',
  },
  {
    'iso_3166_2': 'SV',
    'iso_3166_3': 'SLV',
    'official_name': 'El Salvador',
    'alternate_names': null,
    'emoji': '🇸🇻',
    'phone_calling_code': '503',
  },
  {
    'iso_3166_2': 'GQ',
    'iso_3166_3': 'GNQ',
    'official_name': 'Equatorial Guinea',
    'alternate_names': null,
    'emoji': '🇬🇶',
    'phone_calling_code': '240',
  },
  {
    'iso_3166_2': 'ER',
    'iso_3166_3': 'ERI',
    'official_name': 'Eritrea',
    'alternate_names': null,
    'emoji': '🇪🇷',
    'phone_calling_code': '291',
  },
  {
    'iso_3166_2': 'EE',
    'iso_3166_3': 'EST',
    'official_name': 'Estonia',
    'alternate_names': null,
    'emoji': '🇪🇪',
    'phone_calling_code': '372',
  },
  {
    'iso_3166_2': 'ET',
    'iso_3166_3': 'ETH',
    'official_name': 'Ethiopia',
    'alternate_names': null,
    'emoji': '🇪🇹',
    'phone_calling_code': '251',
  },
  {
    'iso_3166_2': 'FK',
    'iso_3166_3': 'FLK',
    'official_name': 'Falkland Islands (Malvinas)',
    'alternate_names': null,
    'emoji': '🇫🇰',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'FO',
    'iso_3166_3': 'FRO',
    'official_name': 'Faroe Islands',
    'alternate_names': null,
    'emoji': '🇫🇴',
    'phone_calling_code': '298',
  },
  {
    'iso_3166_2': 'FJ',
    'iso_3166_3': 'FJI',
    'official_name': 'Fiji',
    'alternate_names': null,
    'emoji': '🇫🇯',
    'phone_calling_code': '679',
  },
  {
    'iso_3166_2': 'FI',
    'iso_3166_3': 'FIN',
    'official_name': 'Finland',
    'alternate_names': null,
    'emoji': '🇫🇮',
    'phone_calling_code': '358',
  },
  {
    'iso_3166_2': 'FR',
    'iso_3166_3': 'FRA',
    'official_name': 'France',
    'alternate_names': null,
    'emoji': '🇫🇷',
    'phone_calling_code': '33',
  },
  {
    'iso_3166_2': 'GF',
    'iso_3166_3': 'GUF',
    'official_name': 'French Guiana',
    'alternate_names': null,
    'emoji': '🇬🇫',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'PF',
    'iso_3166_3': 'PYF',
    'official_name': 'French Polynesia',
    'alternate_names': null,
    'emoji': '🇵🇫',
    'phone_calling_code': '689',
  },
  {
    'iso_3166_2': 'TF',
    'iso_3166_3': 'ATF',
    'official_name': 'French Southern Territories',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'GA',
    'iso_3166_3': 'GAB',
    'official_name': 'Gabon',
    'alternate_names': null,
    'emoji': '🇬🇦',
    'phone_calling_code': '241',
  },
  {
    'iso_3166_2': 'GM',
    'iso_3166_3': 'GMB',
    'official_name': 'Gambia',
    'alternate_names': null,
    'emoji': '🇬🇲',
    'phone_calling_code': '220',
  },
  {
    'iso_3166_2': 'GE',
    'iso_3166_3': 'GEO',
    'official_name': 'Georgia',
    'alternate_names': null,
    'emoji': '🇬🇪',
    'phone_calling_code': '995',
  },
  {
    'iso_3166_2': 'DE',
    'iso_3166_3': 'DEU',
    'official_name': 'Germany',
    'alternate_names': null,
    'emoji': '🇩🇪',
    'phone_calling_code': '49',
  },
  {
    'iso_3166_2': 'GH',
    'iso_3166_3': 'GHA',
    'official_name': 'Ghana',
    'alternate_names': null,
    'emoji': '🇬🇭',
    'phone_calling_code': '233',
  },
  {
    'iso_3166_2': 'GI',
    'iso_3166_3': 'GIB',
    'official_name': 'Gibraltar',
    'alternate_names': null,
    'emoji': '🇬🇮',
    'phone_calling_code': '350',
  },
  {
    'iso_3166_2': 'GR',
    'iso_3166_3': 'GRC',
    'official_name': 'Greece',
    'alternate_names': null,
    'emoji': '🇬🇷',
    'phone_calling_code': '30',
  },
  {
    'iso_3166_2': 'GL',
    'iso_3166_3': 'GRL',
    'official_name': 'Greenland',
    'alternate_names': null,
    'emoji': '🇬🇱',
    'phone_calling_code': '299',
  },
  {
    'iso_3166_2': 'GD',
    'iso_3166_3': 'GRD',
    'official_name': 'Grenada',
    'alternate_names': null,
    'emoji': '🇬🇩',
    'phone_calling_code': '1-473',
  },
  {
    'iso_3166_2': 'GP',
    'iso_3166_3': 'GLP',
    'official_name': 'Guadeloupe',
    'alternate_names': null,
    'emoji': '🇬🇵',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'GU',
    'iso_3166_3': 'GUM',
    'official_name': 'Guam',
    'alternate_names': null,
    'emoji': '🇬🇺',
    'phone_calling_code': '1-671',
  },
  {
    'iso_3166_2': 'GT',
    'iso_3166_3': 'GTM',
    'official_name': 'Guatemala',
    'alternate_names': null,
    'emoji': '🇬🇹',
    'phone_calling_code': '502',
  },
  {
    'iso_3166_2': 'GG',
    'iso_3166_3': 'GGY',
    'official_name': 'Guernsey',
    'alternate_names': null,
    'emoji': '🇬🇬',
    'phone_calling_code': '44-1481',
  },
  {
    'iso_3166_2': 'GW',
    'iso_3166_3': 'GNB',
    'official_name': 'Guinea-Bissau',
    'alternate_names': null,
    'emoji': '🇬🇼',
    'phone_calling_code': '245',
  },
  {
    'iso_3166_2': 'GN',
    'iso_3166_3': 'GIN',
    'official_name': 'Guinea',
    'alternate_names': null,
    'emoji': '🇬🇳',
    'phone_calling_code': '224',
  },
  {
    'iso_3166_2': 'GY',
    'iso_3166_3': 'GUY',
    'official_name': 'Guyana',
    'alternate_names': null,
    'emoji': '🇬🇾',
    'phone_calling_code': '592',
  },
  {
    'iso_3166_2': 'HT',
    'iso_3166_3': 'HTI',
    'official_name': 'Haiti',
    'alternate_names': null,
    'emoji': '🇭🇹',
    'phone_calling_code': '509',
  },
  {
    'iso_3166_2': 'HM',
    'iso_3166_3': 'HMD',
    'official_name': 'Heard Island and McDonald Islands',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'VA',
    'iso_3166_3': 'VAT',
    'official_name': 'Holy See',
    'alternate_names': 'Holy See (Vatican City State)',
    'emoji': '🇻🇦',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'HN',
    'iso_3166_3': 'HND',
    'official_name': 'Honduras',
    'alternate_names': null,
    'emoji': '🇭🇳',
    'phone_calling_code': '504',
  },
  {
    'iso_3166_2': 'HK',
    'iso_3166_3': 'HKG',
    'official_name': 'Hong Kong',
    'alternate_names': null,
    'emoji': '🇭🇰',
    'phone_calling_code': '852',
  },
  {
    'iso_3166_2': 'HU',
    'iso_3166_3': 'HUN',
    'official_name': 'Hungary',
    'alternate_names': null,
    'emoji': '🇭🇺',
    'phone_calling_code': '36',
  },
  {
    'iso_3166_2': 'IS',
    'iso_3166_3': 'ISL',
    'official_name': 'Iceland',
    'alternate_names': null,
    'emoji': '🇮🇸',
    'phone_calling_code': '354',
  },
  {
    'iso_3166_2': 'IN',
    'iso_3166_3': 'IND',
    'official_name': 'India',
    'alternate_names': null,
    'emoji': '🇮🇳',
    'phone_calling_code': '91',
  },
  {
    'iso_3166_2': 'ID',
    'iso_3166_3': 'IDN',
    'official_name': 'Indonesia',
    'alternate_names': null,
    'emoji': '🇮🇩',
    'phone_calling_code': '62',
  },
  {
    'iso_3166_2': 'IR',
    'iso_3166_3': 'IRN',
    'official_name': 'Iran, Islamic Republic of',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'IQ',
    'iso_3166_3': 'IRQ',
    'official_name': 'Iraq',
    'alternate_names': null,
    'emoji': '🇮🇶',
    'phone_calling_code': '964',
  },
  {
    'iso_3166_2': 'IE',
    'iso_3166_3': 'IRL',
    'official_name': 'Ireland',
    'alternate_names': null,
    'emoji': '🇮🇪',
    'phone_calling_code': '353',
  },
  {
    'iso_3166_2': 'IM',
    'iso_3166_3': 'IMN',
    'official_name': 'Isle of Man',
    'alternate_names': null,
    'emoji': '🇮🇲',
    'phone_calling_code': '44-1624',
  },
  {
    'iso_3166_2': 'IL',
    'iso_3166_3': 'ISR',
    'official_name': 'Israel',
    'alternate_names': null,
    'emoji': '🇮🇱',
    'phone_calling_code': '972',
  },
  {
    'iso_3166_2': 'IT',
    'iso_3166_3': 'ITA',
    'official_name': 'Italy',
    'alternate_names': null,
    'emoji': '🇮🇹',
    'phone_calling_code': '39',
  },
  {
    'iso_3166_2': 'JM',
    'iso_3166_3': 'JAM',
    'official_name': 'Jamaica',
    'alternate_names': null,
    'emoji': '🇯🇲',
    'phone_calling_code': '1-876',
  },
  {
    'iso_3166_2': 'JP',
    'iso_3166_3': 'JPN',
    'official_name': 'Japan',
    'alternate_names': null,
    'emoji': '🇯🇵',
    'phone_calling_code': '81',
  },
  {
    'iso_3166_2': 'JE',
    'iso_3166_3': 'JEY',
    'official_name': 'Jersey',
    'alternate_names': null,
    'emoji': '🇯🇪',
    'phone_calling_code': '44-1534',
  },
  {
    'iso_3166_2': 'JO',
    'iso_3166_3': 'JOR',
    'official_name': 'Jordan',
    'alternate_names': null,
    'emoji': '🇯🇴',
    'phone_calling_code': '962',
  },
  {
    'iso_3166_2': 'KZ',
    'iso_3166_3': 'KAZ',
    'official_name': 'Kazakhstan',
    'alternate_names': null,
    'emoji': '🇰🇿',
    'phone_calling_code': '7',
  },
  {
    'iso_3166_2': 'KE',
    'iso_3166_3': 'KEN',
    'official_name': 'Kenya',
    'alternate_names': null,
    'emoji': '🇰🇪',
    'phone_calling_code': '254',
  },
  {
    'iso_3166_2': 'KI',
    'iso_3166_3': 'KIR',
    'official_name': 'Kiribati',
    'alternate_names': null,
    'emoji': '🇰🇮',
    'phone_calling_code': '686',
  },
  {
    'iso_3166_2': 'KP',
    'iso_3166_3': 'PRK',
    'official_name': "Korea, Democratic People's Republic of",
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'KR',
    'iso_3166_3': 'KOR',
    'official_name': 'Korea, Republic of',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'KW',
    'iso_3166_3': 'KWT',
    'official_name': 'Kuwait',
    'alternate_names': null,
    'emoji': '🇰🇼',
    'phone_calling_code': '965',
  },
  {
    'iso_3166_2': 'KG',
    'iso_3166_3': 'KGZ',
    'official_name': 'Kyrgyzstan',
    'alternate_names': null,
    'emoji': '🇰🇬',
    'phone_calling_code': '996',
  },
  {
    'iso_3166_2': 'LA',
    'iso_3166_3': 'LAO',
    'official_name': "Lao People's Democratic Republic",
    'alternate_names': null,
    'emoji': '🇱🇦',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'LV',
    'iso_3166_3': 'LVA',
    'official_name': 'Latvia',
    'alternate_names': null,
    'emoji': '🇱🇻',
    'phone_calling_code': '371',
  },
  {
    'iso_3166_2': 'LB',
    'iso_3166_3': 'LBN',
    'official_name': 'Lebanon',
    'alternate_names': null,
    'emoji': '🇱🇧',
    'phone_calling_code': '961',
  },
  {
    'iso_3166_2': 'LS',
    'iso_3166_3': 'LSO',
    'official_name': 'Lesotho',
    'alternate_names': null,
    'emoji': '🇱🇸',
    'phone_calling_code': '266',
  },
  {
    'iso_3166_2': 'LR',
    'iso_3166_3': 'LBR',
    'official_name': 'Liberia',
    'alternate_names': null,
    'emoji': '🇱🇷',
    'phone_calling_code': '231',
  },
  {
    'iso_3166_2': 'LY',
    'iso_3166_3': 'LBY',
    'official_name': 'Libya',
    'alternate_names': 'Libyan Arab Jamahiriya',
    'emoji': '🇱🇾',
    'phone_calling_code': '218',
  },
  {
    'iso_3166_2': 'LI',
    'iso_3166_3': 'LIE',
    'official_name': 'Liechtenstein',
    'alternate_names': null,
    'emoji': '🇱🇮',
    'phone_calling_code': '423',
  },
  {
    'iso_3166_2': 'LT',
    'iso_3166_3': 'LTU',
    'official_name': 'Lithuania',
    'alternate_names': null,
    'emoji': '🇱🇹',
    'phone_calling_code': '370',
  },
  {
    'iso_3166_2': 'LU',
    'iso_3166_3': 'LUX',
    'official_name': 'Luxembourg',
    'alternate_names': null,
    'emoji': '🇱🇺',
    'phone_calling_code': '352',
  },
  {
    'iso_3166_2': 'MO',
    'iso_3166_3': 'MAC',
    'official_name': 'Macao',
    'alternate_names': null,
    'emoji': '🇲🇴',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'MK',
    'iso_3166_3': 'MKD',
    'official_name': 'North Macedonia',
    'alternate_names': 'Macedonia, the Former Yugoslav Republic of',
    'emoji': '🇲🇰',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'MG',
    'iso_3166_3': 'MDG',
    'official_name': 'Madagascar',
    'alternate_names': null,
    'emoji': '🇲🇬',
    'phone_calling_code': '261',
  },
  {
    'iso_3166_2': 'MW',
    'iso_3166_3': 'MWI',
    'official_name': 'Malawi',
    'alternate_names': null,
    'emoji': '🇲🇼',
    'phone_calling_code': '265',
  },
  {
    'iso_3166_2': 'MY',
    'iso_3166_3': 'MYS',
    'official_name': 'Malaysia',
    'alternate_names': null,
    'emoji': '🇲🇾',
    'phone_calling_code': '60',
  },
  {
    'iso_3166_2': 'MV',
    'iso_3166_3': 'MDV',
    'official_name': 'Maldives',
    'alternate_names': null,
    'emoji': '🇲🇻',
    'phone_calling_code': '960',
  },
  {
    'iso_3166_2': 'ML',
    'iso_3166_3': 'MLI',
    'official_name': 'Mali',
    'alternate_names': null,
    'emoji': '🇲🇱',
    'phone_calling_code': '223',
  },
  {
    'iso_3166_2': 'MT',
    'iso_3166_3': 'MLT',
    'official_name': 'Malta',
    'alternate_names': null,
    'emoji': '🇲🇹',
    'phone_calling_code': '356',
  },
  {
    'iso_3166_2': 'MH',
    'iso_3166_3': 'MHL',
    'official_name': 'Marshall Islands',
    'alternate_names': null,
    'emoji': '🇲🇭',
    'phone_calling_code': '692',
  },
  {
    'iso_3166_2': 'MQ',
    'iso_3166_3': 'MTQ',
    'official_name': 'Martinique',
    'alternate_names': null,
    'emoji': '🇲🇶',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'MR',
    'iso_3166_3': 'MRT',
    'official_name': 'Mauritania',
    'alternate_names': null,
    'emoji': '🇲🇷',
    'phone_calling_code': '222',
  },
  {
    'iso_3166_2': 'MU',
    'iso_3166_3': 'MUS',
    'official_name': 'Mauritius',
    'alternate_names': null,
    'emoji': '🇲🇺',
    'phone_calling_code': '230',
  },
  {
    'iso_3166_2': 'YT',
    'iso_3166_3': 'MYT',
    'official_name': 'Mayotte',
    'alternate_names': null,
    'emoji': '🇾🇹',
    'phone_calling_code': '262',
  },
  {
    'iso_3166_2': 'MX',
    'iso_3166_3': 'MEX',
    'official_name': 'Mexico',
    'alternate_names': null,
    'emoji': '🇲🇽',
    'phone_calling_code': '52',
  },
  {
    'iso_3166_2': 'FM',
    'iso_3166_3': 'FSM',
    'official_name': 'Micronesia, Federated States of',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'MD',
    'iso_3166_3': 'MDA',
    'official_name': 'Moldova, Republic of',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'MC',
    'iso_3166_3': 'MCO',
    'official_name': 'Monaco',
    'alternate_names': null,
    'emoji': '🇲🇨',
    'phone_calling_code': '377',
  },
  {
    'iso_3166_2': 'MN',
    'iso_3166_3': 'MNG',
    'official_name': 'Mongolia',
    'alternate_names': null,
    'emoji': '🇲🇳',
    'phone_calling_code': '976',
  },
  {
    'iso_3166_2': 'ME',
    'iso_3166_3': 'MNE',
    'official_name': 'Montenegro',
    'alternate_names': null,
    'emoji': '🇲🇪',
    'phone_calling_code': '382',
  },
  {
    'iso_3166_2': 'MS',
    'iso_3166_3': 'MSR',
    'official_name': 'Montserrat',
    'alternate_names': null,
    'emoji': '🇲🇸',
    'phone_calling_code': '1-664',
  },
  {
    'iso_3166_2': 'MA',
    'iso_3166_3': 'MAR',
    'official_name': 'Morocco',
    'alternate_names': null,
    'emoji': '🇲🇦',
    'phone_calling_code': '212',
  },
  {
    'iso_3166_2': 'MZ',
    'iso_3166_3': 'MOZ',
    'official_name': 'Mozambique',
    'alternate_names': null,
    'emoji': '🇲🇿',
    'phone_calling_code': '258',
  },
  {
    'iso_3166_2': 'MM',
    'iso_3166_3': 'MMR',
    'official_name': 'Myanmar',
    'alternate_names': null,
    'emoji': '🇲🇲',
    'phone_calling_code': '95',
  },
  {
    'iso_3166_2': 'NA',
    'iso_3166_3': 'NAM',
    'official_name': 'Namibia',
    'alternate_names': null,
    'emoji': '🇳🇦',
    'phone_calling_code': '264',
  },
  {
    'iso_3166_2': 'NR',
    'iso_3166_3': 'NRU',
    'official_name': 'Nauru',
    'alternate_names': null,
    'emoji': '🇳🇷',
    'phone_calling_code': '674',
  },
  {
    'iso_3166_2': 'NP',
    'iso_3166_3': 'NPL',
    'official_name': 'Nepal',
    'alternate_names': null,
    'emoji': '🇳🇵',
    'phone_calling_code': '977',
  },
  {
    'iso_3166_2': 'NL',
    'iso_3166_3': 'NLD',
    'official_name': 'Netherlands, Kingdom of the',
    'alternate_names': 'Netherlands',
    'emoji': '🇳🇱',
    'phone_calling_code': '31',
  },
  {
    'iso_3166_2': 'NC',
    'iso_3166_3': 'NCL',
    'official_name': 'New Caledonia',
    'alternate_names': null,
    'emoji': '🇳🇨',
    'phone_calling_code': '687',
  },
  {
    'iso_3166_2': 'NZ',
    'iso_3166_3': 'NZL',
    'official_name': 'New Zealand',
    'alternate_names': null,
    'emoji': '🇳🇿',
    'phone_calling_code': '64',
  },
  {
    'iso_3166_2': 'NI',
    'iso_3166_3': 'NIC',
    'official_name': 'Nicaragua',
    'alternate_names': null,
    'emoji': '🇳🇮',
    'phone_calling_code': '505',
  },
  {
    'iso_3166_2': 'NG',
    'iso_3166_3': 'NGA',
    'official_name': 'Nigeria',
    'alternate_names': null,
    'emoji': '🇳🇬',
    'phone_calling_code': '234',
  },
  {
    'iso_3166_2': 'NE',
    'iso_3166_3': 'NER',
    'official_name': 'Niger',
    'alternate_names': null,
    'emoji': '🇳🇪',
    'phone_calling_code': '227',
  },
  {
    'iso_3166_2': 'NU',
    'iso_3166_3': 'NIU',
    'official_name': 'Niue',
    'alternate_names': null,
    'emoji': '🇳🇺',
    'phone_calling_code': '683',
  },
  {
    'iso_3166_2': 'NF',
    'iso_3166_3': 'NFK',
    'official_name': 'Norfolk Island',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'MP',
    'iso_3166_3': 'MNP',
    'official_name': 'Northern Mariana Islands',
    'alternate_names': null,
    'emoji': '🇲🇵',
    'phone_calling_code': '1-670',
  },
  {
    'iso_3166_2': 'NO',
    'iso_3166_3': 'NOR',
    'official_name': 'Norway',
    'alternate_names': null,
    'emoji': '🇳🇴',
    'phone_calling_code': '47',
  },
  {
    'iso_3166_2': 'OM',
    'iso_3166_3': 'OMN',
    'official_name': 'Oman',
    'alternate_names': null,
    'emoji': '🇴🇲',
    'phone_calling_code': '968',
  },
  {
    'iso_3166_2': 'PK',
    'iso_3166_3': 'PAK',
    'official_name': 'Pakistan',
    'alternate_names': null,
    'emoji': '🇵🇰',
    'phone_calling_code': '92',
  },
  {
    'iso_3166_2': 'PW',
    'iso_3166_3': 'PLW',
    'official_name': 'Palau',
    'alternate_names': null,
    'emoji': '🇵🇼',
    'phone_calling_code': '680',
  },
  {
    'iso_3166_2': 'PS',
    'iso_3166_3': 'PSE',
    'official_name': 'Palestine, State of',
    'alternate_names': 'Palestinian Territory, Occupied',
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'PA',
    'iso_3166_3': 'PAN',
    'official_name': 'Panama',
    'alternate_names': null,
    'emoji': '🇵🇦',
    'phone_calling_code': '507',
  },
  {
    'iso_3166_2': 'PG',
    'iso_3166_3': 'PNG',
    'official_name': 'Papua New Guinea',
    'alternate_names': null,
    'emoji': '🇵🇬',
    'phone_calling_code': '675',
  },
  {
    'iso_3166_2': 'PY',
    'iso_3166_3': 'PRY',
    'official_name': 'Paraguay',
    'alternate_names': null,
    'emoji': '🇵🇾',
    'phone_calling_code': '595',
  },
  {
    'iso_3166_2': 'PE',
    'iso_3166_3': 'PER',
    'official_name': 'Peru',
    'alternate_names': null,
    'emoji': '🇵🇪',
    'phone_calling_code': '51',
  },
  {
    'iso_3166_2': 'PH',
    'iso_3166_3': 'PHL',
    'official_name': 'Philippines',
    'alternate_names': null,
    'emoji': '🇵🇭',
    'phone_calling_code': '63',
  },
  {
    'iso_3166_2': 'PN',
    'iso_3166_3': 'PCN',
    'official_name': 'Pitcairn',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': '64',
  },
  {
    'iso_3166_2': 'PL',
    'iso_3166_3': 'POL',
    'official_name': 'Poland',
    'alternate_names': null,
    'emoji': '🇵🇱',
    'phone_calling_code': '48',
  },
  {
    'iso_3166_2': 'PT',
    'iso_3166_3': 'PRT',
    'official_name': 'Portugal',
    'alternate_names': null,
    'emoji': '🇵🇹',
    'phone_calling_code': '351',
  },
  {
    'iso_3166_2': 'PR',
    'iso_3166_3': 'PRI',
    'official_name': 'Puerto Rico',
    'alternate_names': null,
    'emoji': '🇵🇷',
    'phone_calling_code': '1-787, 1-939',
  },
  {
    'iso_3166_2': 'QA',
    'iso_3166_3': 'QAT',
    'official_name': 'Qatar',
    'alternate_names': null,
    'emoji': '🇶🇦',
    'phone_calling_code': '974',
  },
  {
    'iso_3166_2': 'RE',
    'iso_3166_3': 'REU',
    'official_name': 'Réunion',
    'alternate_names': null,
    'emoji': '🇷🇪',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'RO',
    'iso_3166_3': 'ROU',
    'official_name': 'Romania',
    'alternate_names': null,
    'emoji': '🇷🇴',
    'phone_calling_code': '40',
  },
  {
    'iso_3166_2': 'RU',
    'iso_3166_3': 'RUS',
    'official_name': 'Russian Federation',
    'alternate_names': null,
    'emoji': '🇷🇺',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'RW',
    'iso_3166_3': 'RWA',
    'official_name': 'Rwanda',
    'alternate_names': null,
    'emoji': '🇷🇼',
    'phone_calling_code': '250',
  },
  {
    'iso_3166_2': 'BL',
    'iso_3166_3': 'BLM',
    'official_name': 'Saint Barthélemy',
    'alternate_names': null,
    'emoji': '🇧🇱',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'SH',
    'iso_3166_3': 'SHN',
    'official_name': 'Saint Helena, Ascension and Tristan da Cunha',
    'alternate_names': 'Saint Helena',
    'emoji': '🇸🇭',
    'phone_calling_code': '290',
  },
  {
    'iso_3166_2': 'KN',
    'iso_3166_3': 'KNA',
    'official_name': 'Saint Kitts and Nevis',
    'alternate_names': null,
    'emoji': '🇰🇳',
    'phone_calling_code': '1-869',
  },
  {
    'iso_3166_2': 'LC',
    'iso_3166_3': 'LCA',
    'official_name': 'Saint Lucia',
    'alternate_names': null,
    'emoji': '🇱🇨',
    'phone_calling_code': '1-758',
  },
  {
    'iso_3166_2': 'MF',
    'iso_3166_3': 'MAF',
    'official_name': 'Saint Martin (French part)',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'PM',
    'iso_3166_3': 'SPM',
    'official_name': 'Saint Pierre and Miquelon',
    'alternate_names': null,
    'emoji': '🇵🇲',
    'phone_calling_code': '508',
  },
  {
    'iso_3166_2': 'VC',
    'iso_3166_3': 'VCT',
    'official_name': 'Saint Vincent and the Grenadines',
    'alternate_names': null,
    'emoji': '🇻🇨',
    'phone_calling_code': '1-784',
  },
  {
    'iso_3166_2': 'WS',
    'iso_3166_3': 'WSM',
    'official_name': 'Samoa',
    'alternate_names': null,
    'emoji': '🇼🇸',
    'phone_calling_code': '685',
  },
  {
    'iso_3166_2': 'SM',
    'iso_3166_3': 'SMR',
    'official_name': 'San Marino',
    'alternate_names': null,
    'emoji': '🇸🇲',
    'phone_calling_code': '378',
  },
  {
    'iso_3166_2': 'ST',
    'iso_3166_3': 'STP',
    'official_name': 'Sao Tome and Principe',
    'alternate_names': null,
    'emoji': '🇸🇹',
    'phone_calling_code': '239',
  },
  {
    'iso_3166_2': 'SA',
    'iso_3166_3': 'SAU',
    'official_name': 'Saudi Arabia',
    'alternate_names': null,
    'emoji': '🇸🇦',
    'phone_calling_code': '966',
  },
  {
    'iso_3166_2': 'SN',
    'iso_3166_3': 'SEN',
    'official_name': 'Senegal',
    'alternate_names': null,
    'emoji': '🇸🇳',
    'phone_calling_code': '221',
  },
  {
    'iso_3166_2': 'RS',
    'iso_3166_3': 'SRB',
    'official_name': 'Serbia',
    'alternate_names': null,
    'emoji': '🇷🇸',
    'phone_calling_code': '381',
  },
  {
    'iso_3166_2': 'SC',
    'iso_3166_3': 'SYC',
    'official_name': 'Seychelles',
    'alternate_names': null,
    'emoji': '🇸🇨',
    'phone_calling_code': '248',
  },
  {
    'iso_3166_2': 'SL',
    'iso_3166_3': 'SLE',
    'official_name': 'Sierra Leone',
    'alternate_names': null,
    'emoji': '🇸🇱',
    'phone_calling_code': '232',
  },
  {
    'iso_3166_2': 'SG',
    'iso_3166_3': 'SGP',
    'official_name': 'Singapore',
    'alternate_names': null,
    'emoji': '🇸🇬',
    'phone_calling_code': '65',
  },
  {
    'iso_3166_2': 'SX',
    'iso_3166_3': 'SXM',
    'official_name': 'Sint Maarten (Dutch part)',
    'alternate_names': null,
    'emoji': '🇸🇽',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'SK',
    'iso_3166_3': 'SVK',
    'official_name': 'Slovakia',
    'alternate_names': null,
    'emoji': '🇸🇰',
    'phone_calling_code': '421',
  },
  {
    'iso_3166_2': 'SI',
    'iso_3166_3': 'SVN',
    'official_name': 'Slovenia',
    'alternate_names': null,
    'emoji': '🇸🇮',
    'phone_calling_code': '386',
  },
  {
    'iso_3166_2': 'SB',
    'iso_3166_3': 'SLB',
    'official_name': 'Solomon Islands',
    'alternate_names': null,
    'emoji': '🇸🇧',
    'phone_calling_code': '677',
  },
  {
    'iso_3166_2': 'SO',
    'iso_3166_3': 'SOM',
    'official_name': 'Somalia',
    'alternate_names': null,
    'emoji': '🇸🇴',
    'phone_calling_code': '252',
  },
  {
    'iso_3166_2': 'ZA',
    'iso_3166_3': 'ZAF',
    'official_name': 'South Africa',
    'alternate_names': null,
    'emoji': '🇿🇦',
    'phone_calling_code': '27',
  },
  {
    'iso_3166_2': 'GS',
    'iso_3166_3': 'SGS',
    'official_name': 'South Georgia and the South Sandwich Islands',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'SS',
    'iso_3166_3': 'SSD',
    'official_name': 'South Sudan',
    'alternate_names': null,
    'emoji': '🇸🇸',
    'phone_calling_code': '211',
  },
  {
    'iso_3166_2': 'ES',
    'iso_3166_3': 'ESP',
    'official_name': 'Spain',
    'alternate_names': null,
    'emoji': '🇪🇸',
    'phone_calling_code': '34',
  },
  {
    'iso_3166_2': 'LK',
    'iso_3166_3': 'LKA',
    'official_name': 'Sri Lanka',
    'alternate_names': null,
    'emoji': '🇱🇰',
    'phone_calling_code': '94',
  },
  {
    'iso_3166_2': 'SD',
    'iso_3166_3': 'SDN',
    'official_name': 'Sudan',
    'alternate_names': null,
    'emoji': '🇸🇩',
    'phone_calling_code': '249',
  },
  {
    'iso_3166_2': 'SR',
    'iso_3166_3': 'SUR',
    'official_name': 'Suriname',
    'alternate_names': null,
    'emoji': '🇸🇷',
    'phone_calling_code': '597',
  },
  {
    'iso_3166_2': 'SJ',
    'iso_3166_3': 'SJM',
    'official_name': 'Svalbard and Jan Mayen',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': '47',
  },
  {
    'iso_3166_2': 'SZ',
    'iso_3166_3': 'SWZ',
    'official_name': 'Eswatini',
    'alternate_names': 'Swaziland',
    'emoji': '🇸🇿',
    'phone_calling_code': '268',
  },
  {
    'iso_3166_2': 'SE',
    'iso_3166_3': 'SWE',
    'official_name': 'Sweden',
    'alternate_names': null,
    'emoji': '🇸🇪',
    'phone_calling_code': '46',
  },
  {
    'iso_3166_2': 'CH',
    'iso_3166_3': 'CHE',
    'official_name': 'Switzerland',
    'alternate_names': null,
    'emoji': '🇨🇭',
    'phone_calling_code': '41',
  },
  {
    'iso_3166_2': 'SY',
    'iso_3166_3': 'SYR',
    'official_name': 'Syrian Arab Republic',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'TW',
    'iso_3166_3': 'TWN',
    'official_name': 'Taiwan, Province of China',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'TJ',
    'iso_3166_3': 'TJK',
    'official_name': 'Tajikistan',
    'alternate_names': null,
    'emoji': '🇹🇯',
    'phone_calling_code': '992',
  },
  {
    'iso_3166_2': 'TZ',
    'iso_3166_3': 'TZA',
    'official_name': 'Tanzania, United Republic of',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'TH',
    'iso_3166_3': 'THA',
    'official_name': 'Thailand',
    'alternate_names': null,
    'emoji': '🇹🇭',
    'phone_calling_code': '66',
  },
  {
    'iso_3166_2': 'TL',
    'iso_3166_3': 'TLS',
    'official_name': 'Timor-Leste',
    'alternate_names': null,
    'emoji': '🇹🇱',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'TG',
    'iso_3166_3': 'TGO',
    'official_name': 'Togo',
    'alternate_names': null,
    'emoji': '🇹🇬',
    'phone_calling_code': '228',
  },
  {
    'iso_3166_2': 'TK',
    'iso_3166_3': 'TKL',
    'official_name': 'Tokelau',
    'alternate_names': null,
    'emoji': '🇹🇰',
    'phone_calling_code': '690',
  },
  {
    'iso_3166_2': 'TO',
    'iso_3166_3': 'TON',
    'official_name': 'Tonga',
    'alternate_names': null,
    'emoji': '🇹🇴',
    'phone_calling_code': '676',
  },
  {
    'iso_3166_2': 'TT',
    'iso_3166_3': 'TTO',
    'official_name': 'Trinidad and Tobago',
    'alternate_names': null,
    'emoji': '🇹🇹',
    'phone_calling_code': '1-868',
  },
  {
    'iso_3166_2': 'TN',
    'iso_3166_3': 'TUN',
    'official_name': 'Tunisia',
    'alternate_names': null,
    'emoji': '🇹🇳',
    'phone_calling_code': '216',
  },
  {
    'iso_3166_2': 'TR',
    'iso_3166_3': 'TUR',
    'official_name': 'Türkiye',
    'alternate_names': 'Turkey',
    'emoji': '🇹🇷',
    'phone_calling_code': '90',
  },
  {
    'iso_3166_2': 'TM',
    'iso_3166_3': 'TKM',
    'official_name': 'Turkmenistan',
    'alternate_names': null,
    'emoji': '🇹🇲',
    'phone_calling_code': '993',
  },
  {
    'iso_3166_2': 'TC',
    'iso_3166_3': 'TCA',
    'official_name': 'Turks and Caicos Islands',
    'alternate_names': null,
    'emoji': '🇹🇨',
    'phone_calling_code': '1-649',
  },
  {
    'iso_3166_2': 'TV',
    'iso_3166_3': 'TUV',
    'official_name': 'Tuvalu',
    'alternate_names': null,
    'emoji': '🇹🇻',
    'phone_calling_code': '688',
  },
  {
    'iso_3166_2': 'UG',
    'iso_3166_3': 'UGA',
    'official_name': 'Uganda',
    'alternate_names': null,
    'emoji': '🇺🇬',
    'phone_calling_code': '256',
  },
  {
    'iso_3166_2': 'UA',
    'iso_3166_3': 'UKR',
    'official_name': 'Ukraine',
    'alternate_names': null,
    'emoji': '🇺🇦',
    'phone_calling_code': '380',
  },
  {
    'iso_3166_2': 'AE',
    'iso_3166_3': 'ARE',
    'official_name': 'United Arab Emirates',
    'alternate_names': null,
    'emoji': '🇦🇪',
    'phone_calling_code': '971',
  },
  {
    'iso_3166_2': 'GB',
    'iso_3166_3': 'GBR',
    'official_name': 'United Kingdom of Great Britain and Northern Ireland',
    'alternate_names': 'United Kingdom',
    'emoji': '🇬🇧',
    'phone_calling_code': '44',
  },
  {
    'iso_3166_2': 'UM',
    'iso_3166_3': 'UMI',
    'official_name': 'United States Minor Outlying Islands',
    'alternate_names': null,
    'emoji': null,
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'US',
    'iso_3166_3': 'USA',
    'official_name': 'United States of America',
    'alternate_names': 'United States',
    'emoji': '🇺🇸',
    'phone_calling_code': '1',
  },
  {
    'iso_3166_2': 'UY',
    'iso_3166_3': 'URY',
    'official_name': 'Uruguay',
    'alternate_names': null,
    'emoji': '🇺🇾',
    'phone_calling_code': '598',
  },
  {
    'iso_3166_2': 'UZ',
    'iso_3166_3': 'UZB',
    'official_name': 'Uzbekistan',
    'alternate_names': null,
    'emoji': '🇺🇿',
    'phone_calling_code': '998',
  },
  {
    'iso_3166_2': 'VU',
    'iso_3166_3': 'VUT',
    'official_name': 'Vanuatu',
    'alternate_names': null,
    'emoji': '🇻🇺',
    'phone_calling_code': '678',
  },
  {
    'iso_3166_2': 'VE',
    'iso_3166_3': 'VEN',
    'official_name': 'Venezuela, Bolivarian Republic of',
    'alternate_names': 'Venezuela',
    'emoji': '🇻🇪',
    'phone_calling_code': '58',
  },
  {
    'iso_3166_2': 'VN',
    'iso_3166_3': 'VNM',
    'official_name': 'Viet Nam',
    'alternate_names': 'Vietnam',
    'emoji': '🇻🇳',
    'phone_calling_code': '84',
  },
  {
    'iso_3166_2': 'VG',
    'iso_3166_3': 'VGB',
    'official_name': 'Virgin Islands (British)',
    'alternate_names': 'Virgin Islands, British',
    'emoji': '🇻🇬',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'VI',
    'iso_3166_3': 'VIR',
    'official_name': 'Virgin Islands (U.S.)',
    'alternate_names': 'Virgin Islands, U.S.',
    'emoji': '🇻🇮',
    'phone_calling_code': null,
  },
  {
    'iso_3166_2': 'WF',
    'iso_3166_3': 'WLF',
    'official_name': 'Wallis and Futuna',
    'alternate_names': null,
    'emoji': '🇼🇫',
    'phone_calling_code': '681',
  },
  {
    'iso_3166_2': 'EH',
    'iso_3166_3': 'ESH',
    'official_name': 'Western Sahara',
    'alternate_names': null,
    'emoji': '🇪🇭',
    'phone_calling_code': '212',
  },
  {
    'iso_3166_2': 'YE',
    'iso_3166_3': 'YEM',
    'official_name': 'Yemen',
    'alternate_names': null,
    'emoji': '🇾🇪',
    'phone_calling_code': '967',
  },
  {
    'iso_3166_2': 'ZM',
    'iso_3166_3': 'ZMB',
    'official_name': 'Zambia',
    'alternate_names': null,
    'emoji': '🇿🇲',
    'phone_calling_code': '260',
  },
  {
    'iso_3166_2': 'ZW',
    'iso_3166_3': 'ZWE',
    'official_name': 'Zimbabwe',
    'alternate_names': null,
    'emoji': '🇿🇼',
    'phone_calling_code': '263',
  },
]
