export const DIET_FREQUENCIES = [
  '1 time per month or less' as const,
  '2 - 3 times per month' as const,
  '1 - 2 times per week' as const,
  '3 - 4 times per week' as const,
  '5 - 6 times per week' as const,
  '1 time per day' as const,
  '2 - 3 times per day' as const,
  '4 - 5 times per day' as const,
  '6 or more times per day' as const,
]

export type DietFrequency = (typeof DIET_FREQUENCIES)[number]

export const STAPLE_FOODS = [
  'Rice',
  'Wheat',
  'Maize (corn)',
  'Millet',
  'Sorghum',
  'Potatoes',
  'Cassava',
  'Yams',
  'Taro root',
  'Meat',
  'Milk',
  'Eggs',
  'Cheese',
  'Fish',
].map((name) => ({
  id: name,
  name,
}))

export const DRINKS = [
  'Fruit juice',
  'Vegetable juice',
  'Milk',
  'High protein/meal replacement',
  'Soft drinks',
  'Sports drinks',
  'Energy drinks',
  'Alcoholic drinks',
  'Water',
  'Traditional tea',
  'Green tea',
  'Coffee',
  'Traditional drinks',
  'Herbal tea/mixtures',
].map((name) => ({
  id: name,
  name,
}))

// fruits are a subcategory on notion, but they are all included here
export const NON_MEATS = [
  'Oatmeal/cooked cereals',
  'Rice',
  'Corn',
  'Potatoes',
  'Pasta',
  'Sweet potatoes/yam/cassava',
  'Bread',
  'Cooked fruit',
  'Dried/canned fruit',
  'Fresh vegetables/salad',
  'Applesauce',
  'Apples',
  'Bananas',
  'Pineapple',
  'Pears',
  'Peaches, nectarines, or plums',
  'Dried fruit- prunes/ raisins',
  'Grapes',
  'Cantaloupe',
  'Watermelons',
  'Strawberries',
  'Black',
  'Other berries',
  'Oranges, tangerines, or clementines',
  'Grapefruit',
  'Avocado or guacamole',
  'Cooked vegetables',
  'Dried/canned vegetables',
  'Fresh beans',
  'Cooked beans',
  'Dried/canned beans',
  'Fresh nuts',
  'Nut butter',
  'Dairy products',
  'Eggs',
  'Soups',
  'Chili',
  'Meat substitutes',
].map((name) => ({
  id: name,
  name,
}))

export const FATS = [
  'Margarine',
  'Corn oil',
  'Sunflower oil',
  'Canola or rapeseed oil',
  'Olive oil',
  'Oil spray',
  'Lard or animal fat',
].map((name) => ({
  id: name,
  name,
}))

export const SPECIAL_DIETS = [
  'Vegetarian',
  'White meat only',
  'Raw foods only',
  'Weight loss/low carbohydrates diet',
  'Keto/low carb, high fat diet',
  'High protein diet',
  'Low salt diet',
  'Low fat diet',
].map((name) => ({
  id: name,
  name,
}))

// this combines all supplements- notion separates out the herbal supplements
export const SUPPLEMENTS = [
  'Fiber',
  'Beta- carotene/ Vitamin A',
  'Vitamin B',
  'Vitamin Bcomplex',
  'Vitamin C',
  'Vitamin D',
  'Vitamin E',
  'Multivitamins',
  'Eye health supplement',
  'Antacids',
  'Garlic supplement',
  'Joint supplement',
  'Iron',
  'Calcium',
  'Fluoride',
  'Potassium',
  'Magnesium',
  'Selenium',
  'Zinc',
  'Melatonin',
  'Omega-3/ fish oil',
  'Probiotics',
  'Creatine',
  'Lecithin',
  'Plant sterols',
  'Red yeast',
  'Aloe Vera',
  'Ginger',
  'Astragalus',
  'Ginkgo biloba',
  'Bilberry',
  'Ginseng',
  "Cat's claw",
  'Goldenseal',
  'Cayenne',
  'Cinnamon',
  'Grapeseed extract',
  'Cranberry',
  'Kava, kava',
  'Dong Kuai',
  'Milk thistle',
  'Echinacea',
  'Saw palmetto',
  'Evening primrose oil',
  'Siberian ginseng',
  'Feverfew',
  "St. John's wort",
  'Garlic',
  'Valerian',
  'Turmeric',
].map((name) => ({
  id: name,
  name,
}))

export const herbal_supplements = [
  'Aloe Vera',
  'Ginger',
  'Astragalus',
  'Ginkgo biloba',
  'Bilberry',
  'Ginseng',
  "Cat's claw",
  'Goldenseal',
  'Cayenne',
  'Cinnamon',
  'Grapeseed extract',
  'Cranberry',
  'Kava, kava',
  'Dong Kuai',
  'Milk thistle',
  'Echinacea',
  'Saw palmetto',
  'Evening primrose oil',
  'Siberian ginseng',
  'Feverfew',
  "St. John's wort",
  'Garlic',
  'Valerian',
  'Turmeric',
].map((name) => ({
  id: name,
  name,
}))

export const MEATS = [
  'Chicken',
  'Pork',
  'Beef',
  'Fish',
  'Seafood',
  'Game',
  'Cold cuts',
  'Canned meats',
  'Processed meats',
  'Dried meats',
  'Marinated meats',
].map((name) => ({
  id: name,
  name,
}))

export const JUNK_FOOD = [
  'Fried potato chips',
  'Burgers',
  'Pies',
  'Sweets/ dessert',
  'Cakes, cookies',
  'Pizza',
  'Cheese',
  'Ice-cream',
  'Street food',
  'Restaurant food',
  'Exotic cuisines',
].map((name) => ({
  id: name,
  name,
}))

export const EATING_REASONS = [
  'Relaxing/reward',
  'Stress/anxiety',
  'Upset',
  'Boredom',
  'Tired',
  'Social custom',
].map((name) => ({
  id: name,
  name,
}))

export const MEAL_TYPES = [
  'Breakfast',
  'Lunch',
  'Dinner',
  'Snack',
]
