export const ASSESSMENTS = [
  'Head-to-toe Assessment' as const,
  "Women's Health Assessment" as const,
  'Maternity Assessment' as const,
  "Men's Health Assessment" as const,
  'Mental Health Assessment' as const,
  'Child Health Assessment' as const,
  'Gastroenterology' as const,
  'Endocrine' as const,
  'Osteopathy' as const,
  'Trauma' as const,
  'Oncology' as const,
  'Dental' as const,
  'Otolaryngology' as const,
  'Immunology' as const,
  'Urology' as const,
  'Gynecological' as const,
  'Neurology' as const,
  'Anesthetic' as const,
  'Obstetric' as const,
  'Ophthalmology' as const,
  'Geriatric' as const,
  'Pulmonology' as const,
  'Haematology' as const,
  'Dermatology' as const,
  'Paediatric' as const,
  'Rheumatology' as const,
  'Vascular' as const,
  'Cardiology' as const,
  'Psychiatry' as const,
  'Maxillofacial' as const,
  'Nephrology' as const,
]

export const DIAGNOSTIC_TESTS = [
  'Urine Analysis' as const,
  'Malaria' as const,
  'HIV' as const,
  'Pregnancy' as const,
  'Cholesterol' as const,
  'Blood Glucose' as const,
  'Hemoglobin' as const,
  'Uric Acid' as const,
  'Covid 19' as const,
  'Diabetes' as const,
  'Inflammation' as const,
  'Cardiac' as const,
  'Hormone' as const,
  'Thyroid' as const,
  'Bone Metabolism' as const,
  'Gastric Function' as const,
  'Anemia' as const,
  'Tumor' as const,
  'Brain Injury' as const,
  'Angiocapy' as const,
  'Immune System' as const,
  'Renal Function' as const,
  'Nervous System' as const,
  'Blood Pressure' as const,
  'Blood Oxygen Saturation' as const,
  'Body Mass Index' as const,
  'Spirometry FVC' as const,
  'Spirometry FEV' as const,
  'Spirometry PEF' as const,
  'Hepatitis C' as const,
  'Tuberculosis' as const,
  'Body Fat' as const,
  'Bone Mass' as const,
  'Water Weight' as const,
  'Muscle Mass' as const,
  'Body Weight' as const,
  'Basal Metabolic Rate' as const,
  'Typhoid' as const,
  'Syphilis' as const,
  'Chlamydia' as const,
  'Gonorrhea' as const,
  'Hepatitis A/B/C' as const,
  'Herpes Simplex Virus 1 & 2' as const,
  'Trichomonas' as const,
  'Cholera' as const,
  'Abdominal Ultrasound' as const,
  'Renal Ultrasound' as const,
  'Breast Ultrasound' as const,
  'Doppler Ultrasound' as const,
  'Pelvic Ultrasound' as const,
  'Transvaginal Ultrasound' as const,
  'Thyroid Ultrasound' as const,
  'Transrectal Ultrasound' as const,
  'Pregnancy Ultrasound' as const,
  'Chest X-ray' as const,
  'Abdominal X-ray' as const,
  'Kidney, Ureter and Bladder X-ray' as const,
  'Neck X-ray' as const,
  'Hand X-ray' as const,
  'Joint X-ray' as const,
  'Skull X-ray' as const,
  'Temperature' as const,
]

export const EXAMINATIONS = [
  ...ASSESSMENTS,
  ...DIAGNOSTIC_TESTS,
]

export type Assessment = typeof ASSESSMENTS[number]

export type DiagnosticTest = typeof DIAGNOSTIC_TESTS[number]

export type Examination = typeof EXAMINATIONS[number]

/*  SQL to get all examination findings
    select examination_findings.name,
           examination_name,
           category,
           examination_findings.type,
           required,
           options,
           ask_dependent_on,
           ask_dependent_values
      from examination_findings
      join examination_categories on examination_findings.examination_category_id = examination_categories.id
      join examinations on examination_categories.examination_name = examinations.name
  order by examinations.order asc,
           examination_categories.order asc,
           examination_findings.order asc
*/
