export const ADULT_PAC_SYMPTOMS_TABLE_OF_CONTENTS = {
  'Abused patient': 88,
  'Abdominal pain': 44,
  'Aggressive patient': 84,
  'Anaemia': 27,
  'Anal symptoms': 48,
  'Anaphylaxis': 20,
  'Anxiety': 86,
  'Arm symptoms': 64,
  'Back pain': 63,
  'Bites': 22,
  'Blackheads': 67,
  'Blackout': 28,
  'Body pain': 60,
  'Breast symptoms': 43,
  'Breathing difficulty': 38,
  'Burns': 21,
  'Cardiac arrest': 14,
  'Cervical screening': 55,
  'Chest pain': 37,
  'Cholera': 47,
  'Collapse': 28,
  'Coma': 16,
  'Condom broken': 154,
  'Confused patient': 85,
  'Constipation': 48,
  'Convulsion': 19,
  'Cough': 38,
  'Dental symptoms': 36,
  'Diarrhoea': 46,
  'Discharge, genital': 49,
  'Disruptive patient': 84,
  'Dizziness': 29,
  'Ear symptoms': 33,
  'Emergency patient': 14,
  'Eye symptoms': 31,
  'Lump, skin': 67,
  'Lymphadenopathy': 25,
  'Menstrual symptoms': 56,
  'Miserable patient': 86,
  'Mouth symptoms': 35,
  'Face symptoms': 32,
  'Faint': 28,
  'Falls': 28,
  'Fatigue': 26,
  'Fever': 24,
  'Fits': 19,
  'Foot symptoms': 66,
  'Foot care': 66,
  'Fracture': 18,
  'Nail symptoms': 82,
  'Nausea': 45,
  'Neck pain': 64,
  'Needlestick injury': 108,
  'Nose symptoms': 34,
  'Genital symptoms': 49,
  'Glucose': 17,
  'Gum symptoms': 36,
  'Overweight patient': 127,
  'Hair loss': 81,
  'Hand symptoms': 64,
  'Headache': 30,
  'Hearing symptoms': 33,
  'Heartburn': 44,
  'Pain, back': 63,
  'Pain, body/general': 60,
  'Pain, chest': 37,
  'Pain, chronic': 61,
  'Pain, neck': 64,
  'Pallor': 27,
  'Period problems': 56,
  'Pimples': 67,
  'Injured patient': 18,
  'Itch': 67,
  'Rape': 88,
  'Rash': 67,
  'Respiratory arrest': 14,
  'Jaundice': 79,
  'Joint symptoms': 62,
  'Leg symptoms': 65,
  'Lump, neck/axilla/groin': 25,
  'Mouth/Throat symptoms': 35,
  'Scalp symptoms': 80,
  'Scrotal symptoms': 49,
  'Seizures': 19,
  'Self-harm': 83,
  'Sexual problems': 58,
  'Sexually transmitted infections': 49,
  'Skin symptoms': 67,
  'Sleeping difficulty': 87,
  'Smoking': 141,
  'Stings': 22,
  'Stress': 86,
  'Suicidal patient': 83,
  'Syphilis': 53,
  'Tasting difficulty': 35,
  'Teeth symptoms': 36,
  'Throat symptoms': 35,
  'Tiredness': 26,
  'Traumatised patient': 88,
  'Ulcer, genital': 49,
  'Ulcer, skin': 67,
  'Unconscious patient': 16,
  'Urinary symptoms': 59,
  'Vaginal bleeding': 57,
  'Vaginal discharge': 49,
  'Violent patient': 84,
  'Vision symptoms': 31,
  'Vomiting': 45,
  'Warts, genital': 49,
  'Weakness': 26,
  'Weight loss': 23,
  'Wheeze': 39,
  'Wound, acute': 18,
  'Wound, chronic': 76,
}
