export const ADULT_PAC_SYMPTOMS_TABLE_OF_CONTENTS = {
  'Abused patient': 88,
  'Abdominal pain': 44,
  'Aggressive patient': 84,
  'Anaemia': 27,
  'Anal symptoms': 48,
  'Anaphylaxis': 20,
  'Anxiety': 86,
  'Arm symptoms': 64,
  'Back pain': 63,
  'Bites': 22,
  'Blackheads': 67,
  'Blackout': 28,
  'Body pain': 60,
  'Breast symptoms': 43,
  'Breathing difficulty': 38,
  'Burns': 21,
  'Cardiac arrest': 14,
  'Cervical screening': 55,
  'Chest pain': 37,
  'Cholera': 47,
  'Collapse': 28,
  'Coma': 16,
  'Condom broken': 154,
  'Confused patient': 85,
  'Constipation': 48,
  'Convulsion': 19,
  'Cough': 38,
  'Dental symptoms': 36,
  'Diarrhoea': 46,
  'Discharge, genital': 49,
  'Disruptive patient': 84,
  'Dizziness': 29,
  'Ear symptoms': 33,
  'Emergency patient': 14,
  'Eye symptoms': 31,
  'Lump, skin': 67,
  'Lymphadenopathy': 25,
  'Menstrual symptoms': 56,
  'Miserable patient': 86,
  'Mouth symptoms': 35,
  'Face symptoms': 32,
  'Faint': 28,
  'Falls': 28,
  'Fatigue': 26,
  'Fever': 24,
  'Fits': 19,
  'Foot symptoms': 66,
  'Foot care': 66,
  'Fracture': 18,
  'Nail symptoms': 82,
  'Nausea': 45,
  'Neck pain': 64,
  'Needlestick injury': 108,
  'Nose symptoms': 34,
  'Genital symptoms': 49,
  'Glucose': 17,
  'Gum symptoms': 36,
  'Overweight patient': 127,
  'Hair loss': 81,
  'Hand symptoms': 64,
  'Headache': 30,
  'Hearing symptoms': 33,
  'Heartburn': 44,
  'Pain, back': 63,
  'Pain, body/general': 60,
  'Pain, chest': 37,
  'Pain, chronic': 61,
  'Pain, neck': 64,
  'Pallor': 27,
  'Period problems': 56,
  'Pimples': 67,
  'Injured patient': 18,
  'Itch': 67,
  'Rape': 88,
  'Rash': 67,
  'Respiratory arrest': 14,
  'Jaundice': 79,
  'Joint symptoms': 62,
  'Leg symptoms': 65,
  'Lump, neck': 25,
  'Lump, axilla': 25,
  'Lump, groin': 25,
  'Mouth/Throat symptoms': 35,
  'Scalp symptoms': 80,
  'Scrotal symptoms': 49,
  'Seizures': 19,
  'Self-harm': 83,
  'Sexual problems': 58,
  'Sexually transmitted infections': 49,
  'Skin symptoms': 67,
  'Sleeping difficulty': 87,
  'Smoking': 141,
  'Stings': 22,
  'Stress': 86,
  'Suicidal patient': 83,
  'Syphilis': 53,
  'Tasting difficulty': 35,
  'Teeth symptoms': 36,
  'Throat symptoms': 35,
  'Tiredness': 26,
  'Traumatised patient': 88,
  'Ulcer, genital': 49,
  'Ulcer, skin': 67,
  'Unconscious patient': 16,
  'Urinary symptoms': 59,
  'Vaginal bleeding': 57,
  'Vaginal discharge': 49,
  'Violent patient': 84,
  'Vision symptoms': 31,
  'Vomiting': 45,
  'Warts, genital': 49,
  'Weakness': 26,
  'Weight loss': 23,
  'Wheeze': 39,
  'Wound, acute': 18,
  'Wound, chronic': 76,
}

export const ADULT_PAC_CHRONIC_CONDITIONS_TABLE_OF_CONTENTS = {
  'Assess and manage TB infection': 89,
  'How to collect a good sputum specimen for TB': 91,
  'TB: diagnosis': 92,
  'Drug-sensitive TB (DS-TB): routine care': 94,
  'INH mono-resistant TB: routine care': 95,
  'Rifampicin-resistant TB (RR-TB): routine care': 99,
  'HIV: pre-exposure prophylaxis (PrEP)': 106,
  'HIV: post-exposure prophylaxis (PEP)': 108,
  'HIV: diagnosis': 110,
  'HIV: routine care': 111,
  'Cardiovascular disease risk: diagnosis': 127,
  'Cardiovascular disease risk: routine care': 129,
  'Diabetes: diagnosis': 17,
  'Diabetes: routine care': 130,
  'Hypertension: diagnosis': 132,
  'Hypertension: routine care': 133,
  'Heart failure': 135,
  'Stroke': 136,
  'Ischaemic heart disease: initial assessment': 137,
  'Ischaemic heart disease: routine care': 138,
  'Peripheral vascular disease': 139,
  'Hepatitis B (HBV)': 120,
  'Long COVID': 121,
  'The mentally ill patient needing treatment or admission': 140,
  'Tobacco smoking': 141,
  'Alcohol use': 142,
  'Drug use': 142,
  'Depression: diagnosis': 143,
  'Depression: routine care': 144,
  'Anxiety: routine care': 144,
  'Schizophrenia': 146,
  'Dementia': 148,
  'Epilepsy': 149,
  'Chronic arthritis': 151,
  'Gout': 152,
  'Fibromyalgia': 153,
  'Cervical Screening': 55,
  'Contraception': 154,
  'Pregnancy': 157,
  'Routine antenatal care': 159,
  'Routine postnatal care': 164,
  'Manage the pregnant/breastfeeding mother with an unsuppressed VL (≥ 50)': 166,
  'Prevent communicable infections in the newborn': 167,
  'Prevent vertical transmission of HIV': 168,
  'Menopause': 169,
  'Routine palliative care': 170,
  "Address the dying patient's needs": 172,
}

export const ADULT_PAC_OTHER_TABLE_OF_CONTENTS = {
  'Glossary': 6,
  'Prescribe rationally': 7,
  'Screen all patients for COVID-19 and TB': 8,
  'Initial assessment of the patient': 9,
  "Address the patient's general health": 10,
  'COVID-19 diagnosis': 40,
  'Acute COVID-19': 41,
  'Ongoing COVID-19 symptoms': 42,
  'Prevent communicable infections in the newborn': 167,
  'Support the patient taking long-term medication': 173,
  'Protect yourself from occupational infection': 174,
  'Protect yourself from occupational stress': 175,
  'Communicate effectively': 176,
  'Support the patient to make a change': 177,
  'Helpline numbers': 178,
}
