const symptoms_def: {
  category: string
  symptoms: (string | [string, string[]])[]
}[] = [
  {
    'category': 'General',
    'symptoms': [
      'Chills',
      'Cold intolerance',
      'Constipation',
      'Cough',
      'Diarrhea',
      'Dizziness',
      'Dyspepsia',
      'Dyspnea',
      'Fatigue',
      'Fever',
      'Flatulence',
      'Halitosis',
      'Heartburn',
      'Heat intolerance',
      'Hiccups',
      'Hoarse voice',
      'Nausea',
      'Night sweats',
      'Palpitations',
      'Paresthesia',
      'Polydipsia',
      'Polyphagia',
      'Polyuria',
      ['Pruritis', ['itchy skin']],
      'Red eye',
      'Salt, craving',
      'Skin rash',
      'Vomiting',
    ],
  },
  {
    'category': 'Pain',
    'symptoms': [
      'Abdominal pain',
      'Ankle pain',
      'Arm pain',
      'Back pain',
      'Breast pain',
      'Chest pain',
      'Dysmenorrhea',
      'Dysuria',
      'Earache',
      'Elbow pain',
      'Eye pain',
      'Facial pain',
      'Foot and toe pain',
      'Girdle pain',
      'Hand pain',
      'Headache',
      'Finger pain',
      'Hip pain',
      'Jaw pain',
      'Joint pain',
      'Knee pain',
      'Leg pain',
      'Musculoskeletal pain, generalized',
      'Neck pain',
      'Scrotal pain',
      'Shoulder pain',
      'Toothache',
      'Throat pain',
      'Wrist pain',
    ],
  },
  {
    'category': 'Wound/mass',
    'symptoms': [
      'Abdominal mass',
      'Abrasion',
      'Bite',
      'Sting',
      'Bone mass or swelling',
      'Breast mass',
      'Bruise',
      'Burn',
      ['laceration', ['cut']],
      'Groin mass',
      'Facial swelling',
      'Foot ulcer',
      'Foreign body',
      'Genital lesions',
      'Gum swelling',
      'Head mass or swelling',
      'Jaw swelling',
      'Joint swelling',
      'Leg ulcer',
      'Mouth lesions',
      'Scrotal swelling',
      'Ulcer',
    ],
  },
  {
    'category': 'Discharge',
    'symptoms': [
      ['Enuresis', ['bed wetting']],
      'Eye discharge',
      'Fecal incontinence',
      ['Otorrhea', ['ear discharge']],
      ['Rhinorrhea', ['nasal discharge']],
      'Urethral discharge',
      'Urinary incontinence',
      'Vaginal discharge',
    ],
  },
  {
    'category': 'Bleeding',
    'symptoms': [
      'Gum bleeding',
      ['Epistaxis', ['nosebleed']],
      'Hematemesis',
      'Hematuria',
      'Hemoptysis',
      'Melena',
      'Menorrhagia',
      'Rectal bleeding',
      'Vaginal bleeding',
    ],
  },
  {
    'category': 'Loss/difficulty',
    'symptoms': [
      ['Alopecia', ['hair loss']],
      'Amenorrhea',
      'Anosmia',
      'Aphasia',
      'Dysphagia',
      'Difficulty urinating',
      'Erectile dysfunction',
      'Hearing loss',
      'Infertility',
      'Insomnia',
      'Memory loss',
      'Vision loss',
    ],
  },
  {
    'category': 'Abnormal behavior',
    'symptoms': [
      'Confusion',
      'Convulsions',
      'Delusions',
      'Depression',
      'Drop attack',
      'Hallucinations',
      'Mood changes',
      'Psychotic behavior',
      'Violent behavior',
    ],
  },
  {
    'category': 'Abnormal function',
    'symptoms': [
      'Appetite problems',
      'Hearing problems',
      'Movement problems',
      'Menstruation problems',
      'Salivation problems',
      'Sleep problems',
      'Speech problems',
      'Sexual problems',
      'Sweat problems',
      'Taste problems',
      'Thirst problems',
      'Tremors',
      ['Trismus', ['lockjaw']],
      'Visual problems',
      'Voice problems',
      'Writing problems',
      'Weight problems',
    ],
  },
]

export const SYMPTOMS = symptoms_def.flatMap(({ category, symptoms }) => (
  symptoms.map((symptom) =>
    Array.isArray(symptom)
      ? { category, symptom: symptom[0].toLowerCase(), aliases: symptom[1] }
      : { category, symptom: symptom.toLowerCase(), aliases: [] }
  )
))
