#!/usr/bin/env bash
set -euo pipefail

files=$(
  '/test/chatbot/patient/find_nearest_organization/got_location.test.ts'
  '/test/chatbot/patient/find_nearest_organization/send_organization_location.test.ts'
  '/test/chatbot/patient/find_nearest_organization/share_location.test.ts'
  '/test/chatbot/patient/initial_message.test.ts'
  '/test/chatbot/patient/not_onboarded/make_appointment/enter_date_of_birth.test.ts'
  '/test/chatbot/patient/not_onboarded/make_appointment/enter_name.test.ts'
  '/test/chatbot/patient/not_onboarded/make_appointment/enter_national_id_number.test.ts'
  '/test/chatbot/patient/not_onboarded/make_appointment/enter_sex.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/appointment.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/appointment_scheduled.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/cancel_appointment/appointment.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/cancel_appointment/organization.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/main_menu.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/confirm_details_go_back.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/confirm.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/enter_appointment_reason.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/first_scheduling_option/confirm.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/first_scheduling_option/go_back.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/first_scheduling_option/other_times.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/other_scheduling_options/appointment_id.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/onboarded/make_appointment/other_scheduling_options/other_times.test.ts'
  '/test/chatbot/patient/not_onboarded/welcome/organization.test.ts'
  '/test/chatbot/pharmacist/initial_message.test.ts'
  '/test/db/helpers.test.ts'
  '/test/db/migrate.test.ts'
  '/test/events/processor.ts'
  '/test/models/employees.test.ts'
  '/test/models/inventory.test.ts'
  '/test/models/patient_conditions.test.ts'
  '/test/models/patient_findings.test.ts'
  '/test/models/patient_insurance.test.ts'
  '/test/models/patient_measurements.test.ts'
  '/test/models/patient_procedures.ts'
  '/test/models/workflows.test.ts'
  '/test/routes.test.ts'
  '/test/util/inParallel.test.ts'
  '/test/web/invite.test.ts'
  '/test/web/landing-page.test.ts'
  '/test/web/login.test.ts'
  '/test/web/organizations.test.ts'
  '/test/web/organizations/[organization_id]/register.test.ts'
  '/test/web/patients/open_encounter/registration/personal.test.ts'
  '/test/web/patients/open_encounter/registration/this_visit.test.ts'
  '/test/web/patients/open_encounter/triage/additional_tasks_and_investigations.ts'
  '/test/web/patients/open_encounter/triage/brief_history.test.ts'
  '/test/web/patients/open_encounter/triage/measure_vitals.test.ts'
  '/test/web/patients/open_encounter/triage/warning_signs.test.ts'
  '/test/web/patients/start-registration.test.ts'
  '/test/web/providers.test.ts'
  '/test/web/regulator/pharmacies.test.ts'
  '/test/web/regulator/pharmacists.test.ts'
  '/test/web/regulator/pharmacists/[pharmacist_id]/edit.test.ts'
  '/test/web/regulator/pharmacists/invite.test.ts'
)

for file in "${files[@]}"; do
  # Add the import as the very first line of the file
  sed -i '' "1i\\
import { describeParallel, itParallel } from 'test/_helpers/testParallel.ts'
" ".$file"
done