#!/bin/bash
set -euo pipefail

# Array of camelCase variables
camel_vars=(
  acceptedTimes
  actionSendables
  activeLink
  afterTomorrow
  allAllergies
  allDone
  allParams
  alreadyDoctorAndTryingToInviteAsNurseOrVisaVersa
  alreadyKnowRole
  amPm
  appointmentsOfProviderWithGcalEventIds
  appointmentToInsert
  argObj
  argType
  arrayBuffer
  aValue
  baseHour
  baseStyles
  baseUrl
  bodyRect
  buttonRect
  buttonRef
  bValue
  callsToAction
  capLengthAtWhatsAppDescription
  capLengthAtWhatsAppTitle
  certFile
  chatbotToPhone
  closePolyPoints
  compareDate
  conflictIndex
  countryInfo
  createdRegulator
  currentState
  currentStep
  currentTime
  dateString
  dayAvailability
  dayDate
  dayIndex
  dayOffset
  dayStr
  dayStrMinimal
  declinedTimes
  defaultValue
  diffInTime
  distanceInKM
  dosesPerDay
  doseToCompare
  doubleQuotedRegex
  dropdownHeight
  dtDateOnly
  dummyPharmacist
  durationMillis
  employeesResponse
  employmentResult
  encodedKey
  encodedLatitude
  encodedLongitude
  encounterSteps
  endDate
  endTime
  entitySendables
  errorMessage
  exactMatchingInvites
  existingAvailability
  existingAvailabilityEvents
  existingEmployees
  existingKin
  existingPharmacyEmployment
  existingPharmacyEmployments
  expectedLink
  expectedLinks
  expiresInAnHourSql
  facePictureMedia
  familyMembers
  familyName
  familyValues
  fileBlob
  fileContent
  filePath
  fillPoints
  fillStyle
  filteredAvailableTimes
  filteredOptions
  findMatch
  firstAvailable
  firstCallArgs
  firstDayOfNextMonth
  firstDayOfThisMonth
  firstOfferedTime
  firstOtherTime
  firstResult
  firstTime
  firstTimeEnd
  firstTimeStart
  firstWeekDaysOfLastMonth
  formattedTime
  formDisplay
  formElement
  freeBusy
  fullClassName
  gcalEventIds
  gcalItem
  getEmployees
  getLocationAddress
  getNurseRegistrationSteps
  getPersonalResponse
  getProfessionalResponse
  getResponse
  gettingTokens
  getWalkingDistance
  givenName
  googleApisUrl
  googleClient
  gradeDropReasons
  hasBodyPassingValidation
  hasDisplay
  hasExistingNote
  hasOwn
  hasOwnProperty
  hasPermissions
  hasStructured
  hasUnicodeWord
  healthWorkerGoogleClient
  historyItems
  hourMod
  hourStr
  hubChallenge
  hubMode
  hubVerifyToken
  hwQuery
  inDir
  inMemoryCache
  inputDate
  inputElement
  insertedEvent
  insertedMedia
  insertEvent
  insertionOrder
  insertionOrders
  invitedByEmail
  invitedHw
  invitedPharmacist
  invitesResponse
  invitesWithEmails
  isInDoctorReview
  isLast
  isRemoving
  isSelectAll
  isSelectedAll
  isShowPreview
  keyFile
  lastDayOfLastMonth
  lastDayOfThisMonth
  lastMonthInt
  lastMonthYearInt
  lastResult
  lastWeekDaysOfNextMonth
  latitudeMatch
  licenceNumber
  linePoints
  lineStyle
  linksSorted
  loadMore
  longitudeMatch
  longString
  mainTerm
  manufacturedMedication
  matchingDrugs
  matchingProvider
  mediaData
  messageBody
  migrationFile
  migrationName
  migrationTargets
  minuteStr
  mobileActiveIndex
  monthStr
  moreSlots
  nationalIdMedia
  navBarRef
  newDiagnosis
  newMap
  newNurse
  newPharmacist
  newSelected
  newTimeWindows
  nextComorbidities
  nextConditionState
  nextMedications
  nextMonthInt
  nextMonthYearInt
  nonDeclinedTimes
  nounInflector
  nurseEmployment
  nursePracticingCertMedia
  oauthParams
  objectProto
  offeredTime
  onClick
  oneDay
  oneDayBelowThreeMonths
  oneDayBelowTwoYears
  organizationAdmin
  organizationAdminName
  organizationConsumables
  organizationDisplayName
  organizationName
  originalLog
  otherTime
  pageContents
  parseUpsert
  patientAddress
  patientAllergies
  patientAllergiesAfterRemoving
  patientBefore
  patientEncounter
  patientResult
  payloadFormatter
  pharmacyEmployments
  phoneNumbers
  phoneToChatbotName
  postMessageRoute
  postResponse
  preExistingConditions
  prettyTime
  previous_value
  priorityStyles
  proxyHeaders
  proxyRequest
  queryResult
  queryString
  quotedStrings
  randomAddress
  readResult
  reAsciiWord
  reComboHalfMarksRange
  redirectLocation
  redisUrl
  registrationCardMedia
  registrationDetails
  registrationFormState
  rejectNow
  reOptMod
  requestParams
  resolveNow
  responseFormat
  responseToSend
  reUnicodeWords
  rsApos
  rsAstralRange
  rsBreak
  rsBreakRange
  rsCombo
  rsComboMarksExtendedRange
  rsComboMarksRange
  rsComboMarksSupplementRange
  rsComboRange
  rsComboSymbolsRange
  rsDigit
  rsDingbat
  rsDingbatRange
  rsEmoji
  rsFitz
  rsLower
  rsLowerRange
  rsMathOpRange
  rsMisc
  rsMiscLower
  rsMiscUpper
  rsModifier
  rsNonAstral
  rsNonCharRange
  rsOptContrLower
  rsOptContrUpper
  rsOptJoin
  rsOptVar
  rsOrdLower
  rsOrdUpper
  rsPunctuationRange
  rsRegional
  rsSeq
  rsSurrPair
  rsUpper
  rsUpperRange
  rsVarRange
  rsZWJ
  sameAmPm
  scheduleDescriptions
  search_by
  searchParams
  secondDayBusyTime
  secondDayEnd
  secondDayStart
  secondOfferedTime
  secondTimeEnd
  secondTimeStart
  sectionIds
  sectionTitles
  seedFile
  seedName
  seenValues
  selectedDistrict
  selectedPharmacies
  selectedPharmacy
  selectedPriority
  selectedProvince
  selectedSupervisors
  selectedWard
  shortToLong
  shouldOpenUpward
  showDependents
  showGuardians
  showNextOfKin
  showNote
  showPatientCohabitation
  singleDosage
  singleQuotedRegex
  sizeStyles
  slotsWithDates
  spaceAbove
  spaceBelow
  stackLine
  startDate
  startTime
  stepIndex
  stepState
  stopEducationReasons
  streamReader
  streetParts
  styleClass
  successMessage
  successMessages
  tableName
  tableRow
  testCases
  testDoctor
  testPatient
  testPatient1
  testPatient2
  testPatient3
  testPatient4
  testPatient5
  testPatient6
  testPatient7
  testPatient8
  textRegex
  threeMonths
  threeWeeks
  timeEnd
  timeMax
  timeMin
  timeStart
  timeString
  timeWindow
  timeWindows
  todayDate
  todayIndex
  toDecline
  toInsert
  tokenInfo
  topLevelTables
  toPost
  toString
  totalDaysInLastMonth
  totalDaysInThisMonth
  totalDosage
  twentyDays
  twentyFourMb
  twoYears
  unhandledMessages
  uniqueSlots
  updatedPharmacist
  useClassName
  validEvaluations
  variantStyles
  verifyToken
  videoId
  videoQuality
  viewportHeight
  vitalKey
  whatsappOne
  whatsappResponse
  whatsappResponses
  whatsappTwo
  withInvitees
  withoutInvitees
)

# Function to convert camelCase to snake_case
to_snake_case() {
    echo "$1" | gsed 's/\([A-Z]\)/_\L\1/g'
}

# Loop and replace
for camel in "${camel_vars[@]}"; do
    snake=$(to_snake_case "$camel")
    
    # Replace in all files (adjust file pattern as needed)
    find . -type f \( -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" \) -exec gsed -i "s/\b$camel\b/$snake/g" {} +
done