name: Deploy Virtual Hospitals Africa App to AWS

on:
  push:
    branches:
      - main
      - aws

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push events-image to Amazon ECR
        id: build-events-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          SHA: ${{ github.sha }}
        run: |
          docker buildx build \
            -f Dockerfile.vha-events-processor \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHA-events \
            --platform linux/arm64 \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push .

      - name: Build, tag, and push web-image to Amazon ECR
        id: build-web-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          SHA: ${{ github.sha }}
        run: |
          docker buildx build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHA \
            --platform linux/arm64 \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push .


      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ECR_REGISTRY,ECR_REPOSITORY,SHA
          script: |
            set -euo pipefail

            # Login to ECR
            aws ecr get-login-password --region af-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

            # Remove all but the latest 2 images (events + web)
            docker images | awk 'NR > 3 { print $3 }' | xargs docker rmi || true

            # Pull the latest images
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$SHA
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$SHA-events

            # Stop and remove existing containers if they exists
            docker stop vha-app || true
            docker rm vha-app || true
            docker stop vha-events || true
            docker rm vha-events || true

            # Run the new web container
            docker run -d \
              --name vha-app \
              --restart unless-stopped \
              -p 80:8000 \
              --env-file /home/ec2-user/.env \
              --log-driver=awslogs \
              --log-opt awslogs-region=af-south-1 \
              --log-opt awslogs-group=/docker/virtual-hospitals-africa \
              --log-opt awslogs-stream=vha-app \
              $ECR_REGISTRY/$ECR_REPOSITORY:$SHA

            docker run -d \
              --name vha-events \
              --restart unless-stopped \
              --env-file /home/ec2-user/.env \
              --log-driver=awslogs \
              --log-opt awslogs-region=af-south-1 \
              --log-opt awslogs-group=/docker/virtual-hospitals-africa \
              --log-opt awslogs-stream=vha-events \
              $ECR_REGISTRY/$ECR_REPOSITORY:$SHA-events

            docker ps | grep vha
            echo "Deployment complete"
