name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  BUILD_STRING: '${{ github.run_number }}-${{ github.sha }}'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-deno

      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: Run check
        run: deno task check

  test_web:
    uses: ./.github/workflows/test-with-db.yml
    with:
      setup-lfs: true
      artifact-name: test-web-logs
      build: |
        deno task db:restore snomed
        deno task db:migrate all
        deno task build
      run: |
        deno task test --use-build test/web/patients/open_encounter/triage/warning_signs.test.ts

  test_non_web:
    uses: ./.github/workflows/test-with-db.yml
    with:
      setup-lfs: true
      artifact-name: test-non-web-logs
      build: |
        deno task db:restore snomed
        deno task db:migrate all
      run: |
        deno task test --ignore=test/web

  # TODO turn back on
  # test_chatbot:
  #   uses: ./.github/workflows/test-with-db.yml
  #   with:
  #     setup-lfs: true
  #     artifact-name: test-chatbot-logs
  #     run: |
  #       deno task db:restore snomed
  #       deno task db:migrate all
  #       deno task test:chatbot

  test_migrations:
    uses: ./.github/workflows/test-with-db.yml
    with:
      artifact-name: test-migrations-logs
      build: deno task db:migrate latest
      run: |
        deno task db:migrate to snomed_inferred
        deno task db:migrate latest

  build_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t vha .

  compile_web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-deno

      - name: Build web
        run: deno task build

      - name: Compile web
        run: deno task compile:web

  compile_chatbot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-deno

      - name: Compile chatbot
        run: deno task compile:chatbot
